### ISSUE TITLE
User groups are ignored when run as service

### ISSUE THREAD

**Issue by mknapik** [chef-cookbooks/jenkins#205]
I installed Jenkins with Chef and even though I added `jenkins` to `rvm` group my job defined as follows:
```bash
#!/bin/bash
whoami
groups
```
shows
```
jenkins
jenkins
```
as a result.

It was an issue for me as I needed process owner to be the member of `rvm` group.

**Comment by mknapik** [comment]
@schisamo As more and more people are running into this problem I'm ready to create a pull request if you're willing to include the solution in the cookbook.

**Comment by pedrocarrico** [comment]
@mknapik  :+1:

**Comment by tzookb** [comment]
@mknapik :+1: wish I could know how to help :/

**Comment by umgws** [comment]
first change groupID in /etc/passwd file for jenkins user, then delete jenkins group in /etc/group and then restart it /etc/init.d/jenkins restart
after that jenkins will run with jenkins user and your-custom-assigned-group

**Comment by marpada** [comment]
Please re-open and fix

**Comment by greathouse** [comment]
This is definitely not an edge case. We would like to allow jenkins to run in the docker group to allow Jenkins to build docker containers.

**Comment by iennae** [comment]
This fix for this has been merged with the latest release of the cookbook 4.0.1. Thanks for all of your patience folks.
