### ISSUE TITLE
function to allow changing the update center's URL

### ISSUE THREAD

**Issue by xbeta** [chef-cookbooks/jenkins#295]
We are on LTS line of the Jenkins and would love to have a way to also update the Update Center's update URL for LTS line

the url : `https://updates.jenkins-ci.org/stable/update-center.json`

**Comment by docwhat** [comment]
I have done something to do this, but it needs support from the cookbook since it ignores the URL when using the `jenkins_plugin` resource/provider.

My work around:

```
# attributes/plugin.rb

# You could add code to detect if the build is LTS or not (if it is three parts, it's LTS) and use the default
# unstable update-center.json for non-LTS builds.
default['mycookbook']['remote-plugin-data']['url'] = "https://updates.jenkins-ci.org/stable-#{node['jenkins']['master']['version'].split('.')[0..1].join('.')}/update-center.json"
```

```
# recipes/plugins.rb
jenkins_script 'change update url' do
  command <<-EOH
  import hudson.model.UpdateCenter;
  import hudson.model.UpdateSite;
  import hudson.util.PersistedList;
  import jenkins.model.Jenkins

  site = '#{node['mycookbook']['remote-plugin-data']['url']}'
  PersistedList<UpdateSite> sites = Jenkins.getInstance().getUpdateCenter().getSites();
  for (UpdateSite s : sites) {
    if (s.getId().equals(UpdateCenter.ID_DEFAULT))
      sites.remove(s);
  }
  sites.add(new UpdateSite(UpdateCenter.ID_DEFAULT, site));
  EOH
end

# Work around for bug #295
remote_file File.join(Chef::Config[:file_cache_path], 'update-center.json') do
  source node['mycookbook']['remote-plugin-data']['url']
  backup false
  sensitive true
  mode 0644
end

jenkins_plugin('greenballs')
# ... etc.
```

This is because [`ensure_update_center_present!`](https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/_helper.rb#L385) ignores the update-center URL in Jenkins and provides its own (which is the unstable/latest list).

**Comment by xbeta** [comment]
@docwhat do you have a change  that you can send a PR?  I would love to review it, but unfortunately I cannot approve anything as I'm not the owner of this repo.

**Comment by docwhat** [comment]
@xbeta Not really... there are other parts of the cookbook that need cleaning (like `ensure_update_center_present!`) that I'm hesitant to make changes to.

If the authors are willing to accept a stack of changes to clean things up (e.g. a lot of little changes) and don't mind me stomp around their code, I'm willing to put the effort into a PR.

My concern is that if I put a bunch of effort into this that it'll be rejected.  If an author came and said it would be okay to make a bunch of cleanups WRT to the update center URLs then I'd probably do it.

**Comment by cheeseplus** [comment]
I've mucked with this to let this be contructable via `node['jenkins']['master']['mirror']` and `node['jenkins']['master']['channel']`. We've also changed the default to `stable` as that seems far more sensible. I'm going to close out this issue given the age and that we've addressed the initial report but please open a new issue if the behaviour isn't flexible enough and we will get on it.
