### ISSUE TITLE
Using source option and latest version : `jenkins_plugin` still requires plugin_universe

### ISSUE THREAD

**Issue by Brantone** [chef-cookbooks/jenkins#387]
I have a highly customized Jenkins plugin that's not (yet) in the official Jenkins plugin repository, so was hoping to use the source option and link directly to the hpi.
Unfortunately it barfs at https://github.com/opscode-cookbooks/jenkins/blob/master/libraries/plugin.rb#L245
because 

```
NoMethodError
    -------------
    undefined method `[]' for nil:NilClass
```

**Comment by schisamo** [comment]
What happens if you set a value in the `version` attribute?

**Comment by cheeseplus** [comment]
Closing for non-response - we're generally aware of plugin issues that will be covered under a rewrite.

**Comment by Brantone** [comment]
Yikes, I forgot I even had this open, sorry 'bout that.  :( 
Yeah, close it, it was a long time ago and can't fully recall the angle I was coming from. If I encounter it again, I'll re-opn.
