### ISSUE TITLE
Updating and uninstalling jenkins plugins with the jenkins_plugin resource does not work

### ISSUE THREAD

**Issue by daften** [chef-cookbooks/jenkins#389]
I have this in my chef cookbook:
```
# Uninstall core plugins
jenkins_plugins = %w(
  cvs
  javadoc
  maven-plugin
  subversion
)
jenkins_plugins.each do |plugin|
  jenkins_plugin plugin do
    action :uninstall
    notifies :execute, 'jenkins_command[reload-configuration]', :delayed
    notifies :execute, 'jenkins_command[safe-restart]', :delayed
  end
end

# Update core plugins
jenkins_plugins = %w(
  credentials
  git-client
  mailer
  matrix-auth
  junit
  matrix-project
  antisamy-markup-formatter
  pam-auth
  script-security
  ssh-credentials
  translation
  windows-slaves
)
jenkins_plugins.each do |plugin|
  jenkins_plugin plugin do
    notifies :execute, 'jenkins_command[reload-configuration]', :delayed
    notifies :execute, 'jenkins_command[safe-restart]', :delayed
  end
end
```

The output is as expected, e.g.
```
Recipe: jenkins_digipolis::jenkins
  * jenkins_plugin[cvs] action uninstall
  Recipe: <Dynamically Defined Resource>
    * file[/var/lib/jenkins/plugins/cvs.jpi] action delete
      - delete file /var/lib/jenkins/plugins/cvs.jpi
    * directory[/var/lib/jenkins/plugins/cvs] action delete
      - delete existing directory /var/lib/jenkins/plugins/cvs
    - Uninstall jenkins_plugin[cvs]
```

However, the plugins aren't updated and uninstalled according to the UI.

**Comment by jeffersongirao** [comment]
The same is happening to me with Jenkins 1.609. While investigating it I noticed that it actually seems like an issue with jenkins-cli.jar. It works good when you install a plugin using just a name (getting the latest) but it fails when using an url or file path (that what the jenkins_plugin is doing under the hood).

**Comment by jeffersongirao** [comment]
Maybe related: https://issues.jenkins-ci.org/browse/JENKINS-29065

**Comment by adamb-altiscale** [comment]
I just ran into something similar. Its very likely that this is because you are trying to update core plugins, ie plugins that are bundled with the core jenkins install. See https://wiki.jenkins-ci.org/display/JENKINS/Pinned+Plugins for details. To workaround;
```
  file "#{node['jenkins']['master'].home}/plugins/#{plugin}.jpi.pinned" do
    content ''
    mode '0644'
    owner node['jenkins']['master']['user']
    group node['jenkins']['master']['group']
  end
```
inside your `jenkins_plugins.each` block

**Comment by daften** [comment]
That indeed works, thanks.
I won't do this anymore, because I want to review updates again, but thanks! :)

**Comment by adamb-altiscale** [comment]
This is necessary even if you use `jenkins_plugin` to install a specific version, which is what I do, and how I review and select updates.
