### ISSUE TITLE
`jenkins_plugin` resource is updated on every converge

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/jenkins#406]
I think this is ultimately a Jenkins problem, but I'm putting it in here while I research it. I'm guessing others using this cookbook will encounter it.

On every chef run (jenkins cookbook v2.3.1, chef 12.4.1, jenkins v1.609.3 LTS), I'm seeing the same plugin install actions firing (not unique to this plugin, happens with 10-15 of them):

```
  * jenkins_plugin[cvs] action install
  Recipe: <Dynamically Defined Resource>
    * remote_file[/var/chef/cache/cvs-2.12.plugin] action create (up to date)
    * remote_file[/var/chef/cache/jenkins-cli.jar] action create (up to date)
    - Upgrade jenkins_plugin[cvs] from 2.11 to 2.12
```

I've tried restarting jenkins in between runs, but it seems like Jenkins is actually never unpacking the new plugin:

```
# sha256sum /var/chef/cache/cvs-2.12.plugin 
6e6dfd35e8501bf5f84a9d43d210db61165ce51a606327fc81f2efc5208478ba  /var/chef/cache/cvs-2.12.plugin

# unzip /var/chef/cache/cvs-2.12.plugin
# grep -i plugin-version META-INF/MANIFEST.MF 
Plugin-Version: 2.12

# sha256sum /var/lib/jenkins/plugins/cvs.jpi 
6e6dfd35e8501bf5f84a9d43d210db61165ce51a606327fc81f2efc5208478ba  cvs.jpi

# grep -i plugin-version /var/lib/jenkins/plugins/cvs/META-INF/MANIFEST.MF 
Plugin-Version: 2.11
```

I'm thinking this a jenkins bug since I can reproduce it without Chef, just running the CLI commands by hand. I'm just wondering if, when a workaround is found, we should add to the cookbook too.

**Comment by martinb3** [comment]
I ended up finding [JENKINS-12514](https://issues.jenkins-ci.org/browse/JENKINS-12514), which describes the scenario where an `.hpi` of a plugin was shipped with Jenkins itself, and that version constantly persists, even when .jpi upgraded plugins are installed.

I tested if this was true for my example using these commands:
```
# mv /var/lib/jenkins/war/WEB-INF/plugins/cvs.hpi /tmp/nonchef-cvs.hpi
# service jenkins restart
ok: run: jenkins: (pid 14918) 1s
# grep -i plugin-version /var/lib/jenkins/plugins/cvs/META-INF/MANIFEST.MF 
Plugin-Version: 2.12
```

As you can see, now the plugin has been actually upgraded. Should we add a workaround that, if an `.hpi` for the plugin exists in the war file, we remove it, so that upgrades to plugins actually work? Or should this be a workaround in individual implementation cookbooks?

I'm leaning towards the latter, but wanted to document here.

**Comment by wenslayer** [comment]
I'm experiencing this problem as well. Every Chef runs says it's updating the plugin (that comes with Jenkins), but it never gets updated.

Excerpt from the Chef run (I'll look at the cvs plugin in this instance):
```
...
==> default:   Recipe: <Dynamically Defined Resource>
==> default:     * remote_file[/var/chef/cache/cvs-2.12.plugin] action create
==> default:  (up to date)
==> default:     - Upgrade jenkins_plugin[cvs] from 2.11 to 2.12
==> default: Recipe: dbl_orchestration::chef_ci
==> default:   * jenkins_plugin[javadoc] action install
==> default: 
...
==> default:   * service[jenkins] action restart
==> default: [2015-10-29T18:40:32+00:00] INFO: service[jenkins] restarted
==> default: 
==> default:     - restart service service[jenkins]
==> default: 
==> default: [2015-10-29T18:40:32+00:00] INFO: Chef Run complete in 84.065463877 seconds
```

But then examining the files, it looks like the recipe isn't even updating the plugin files that Jenkins uses:
```
# unzip -p /var/chef/cache/cvs-2.12.plugin META-INF/MANIFEST.MF | grep Plugin-Version
Plugin-Version: 2.12

# unzip -p /var/lib/jenkins/plugins/cvs.jpi META-INF/MANIFEST.MF | grep Plugin-Version
Plugin-Version: 2.11

# grep Plugin-Version /var/lib/jenkins/plugins/cvs/META-INF/MANIFEST.MF 
Plugin-Version: 2.11
```

According to [JENKINS-12514](https://issues.jenkins-ci.org/browse/JENKINS-12514), at least the .jpi file should be updated. I have no .hpi files in /var/lib/jenkins/plugins.

BTW, I'm using Jenkins LTS 1.625.1.

Any ideas?

**Comment by daniel-beck** [comment]
Jenkins resets all plugins that are bundled to their bundled version on startup, unless a `PLUGIN.hpi.pinned` marker file exists. Is that what you're seeing here?

**Comment by martinb3** [comment]
There was no `.pinned` marker file when I investigated this. Is this something Jenkins should create?

**Comment by daniel-beck** [comment]
Yes, when you update the plugin through any of the means provided by Jenkins. When you mess with the file system, you are expected to know what you are doing.

https://wiki.jenkins-ci.org/display/JENKINS/Pinned+Plugins

**Comment by martinb3** [comment]
@daniel-beck For the record, I believe we are using means provided by Jenkins. We're not messing with the filesystem -- we're calling `install-plugin` using the Jenkins CLI and passing it a path -- https://github.com/chef-cookbooks/jenkins/blob/master/libraries/plugin.rb#L316. Perhaps that's something that the Jenkins CLI doesn't handle correctly?

**Comment by daniel-beck** [comment]
@martinb3 Thanks for the clarification. In this case, this is indeed a problem. I'll take a look.

**Comment by daniel-beck** [comment]
@martinb3 This is a bug in the `install-plugin` CLI command that is being tracked as [JENKINS-29726](https://issues.jenkins-ci.org/browse/JENKINS-29726).

**Comment by martinb3** [comment]
Thanks for the follow up @daniel-beck -- cheers! :)

**Comment by cheeseplus** [comment]
Closing this one out as it looks like it was resolved upstream for 2.x
