### ISSUE TITLE
"Secret text" credential type?

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/jenkins#407]
As far as I can tell, this cookbook doesn't support all of the credential types that Jenkins offers. It's missing "secret file", "secret text", and "certificate" which are all available on the latest Jenkins (in addition to password and private key types). Just opening this as a placeholder to add it at some point.

**Comment by martinb3** [comment]
`org.jenkinsci.plugins.plaincredentials.impl.StringCredentialsImpl` is specifically the one I'm looking for.

**Comment by schisamo** [comment]
This should have been fixed as part of https://github.com/chef-cookbooks/jenkins/pull/410. The new resource is named `jenkins_secret_text_credentials`.

**Comment by martinb3** [comment]
Thanks @schisamo!

**Comment by schisamo** [comment]
Don't thank me @martinb3...thank @miguelaferreira for an awesome contribution!

**Comment by miguelaferreira** [comment]
There is still the possibility to add the "secret file" credential type. I can do that if there's the need for it.

**Comment by martinb3** [comment]
I'm sure someone could use it @miguelaferreira, but I'm all set right now. Thank you! :)
