### ISSUE TITLE
Cookbook fails on 32-bit CentOS

### ISSUE THREAD

**Issue by lshort** [chef-cookbooks/jenkins#417]
On 32-bit CentOS 6.5 or 6.7, the cookbook fails at the point of installing runit.  If I add a repo with runit-2.1.1, it then hangs at
- ruby_block[wait for jenkins-slave service socket] action run

Full output for that case is at http://pastebin.com/N5YLRJYy

**Comment by nkadel-skyhook** [comment]
Which chef client or chefdk are you running?

**Comment by cheeseplus** [comment]
We don't support or test any 32bit operating systems so closing this out.
