### ISSUE TITLE
remote_file("/var/lib/jenkins/jenkins.war") do Response body length ... does not match HTTP Content-Length header 0.

### ISSUE THREAD

**Issue by piousbox** [chef-cookbooks/jenkins#419]
Running the jenkins::server recipe on a clean ubuntu fails with the following error:

    ================================================================================
    Error executing action `create` on resource 'remote_file[/var/lib/jenkins/jenkins.war]'
    ================================================================================
    
    Chef::Exceptions::ContentLengthMismatch
    ---------------------------------------
    Response body length 54798212 does not match HTTP Content-Length header 0.
    
    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/jenkins/recipes/server.rb
    
    110: remote_file File.join(home_dir, "jenkins.war") do
    111:   source "#{node['jenkins']['mirror']}/war/#{node['jenkins']['server']['version']}/jenkins.war"
    112:   checksum node['jenkins']['server']['war_checksum'] unless node['jenkins']['server']['war_checksum'].nil?
    113:   owner node['jenkins']['server']['user']
    114:   group node['jenkins']['server']['group']
    115:   notifies :restart, "runit_service[jenkins]"
    116:   notifies :create, "ruby_block[block_until_operational]"
    117: end
    118: 
    
    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/jenkins/recipes/server.rb:110:in `from_file'
    
    remote_file("/var/lib/jenkins/jenkins.war") do
      provider Chef::Provider::RemoteFile
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      path "/var/lib/jenkins/jenkins.war"
      backup 5
      atomic_update true
      source ["http://mirrors.jenkins-ci.org/war/latest/jenkins.war"]
      use_etag true
      use_last_modified true
      declared_type :remote_file
      cookbook_name "jenkins"
      recipe_name "server"
      owner "jenkins"
      group "nogroup"
    end

**Comment by schisamo** [comment]
It sounds like a proxy might be getting in the way. Can you attempt a simple `wget` of the WAR url (`http://mirrors.jenkins-ci.org/war/latest/jenkins.war`)?

**Comment by piousbox** [comment]
That's right, a proxy issue.
