### ISSUE TITLE
ERROR: undefined method `provides' for Chef::Provider::JenkinsCommand:Class

### ISSUE THREAD

**Issue by VijayaKumarSoman** [chef-cookbooks/jenkins#426]
## Relevant File Content:

/var/chef/cache/cookbooks/jenkins/libraries/command.rb:

 40:    end
 41:  end
 42:  
 43:  class Chef
 44:    class Provider::JenkinsCommand < Provider::LWRPBase
 45:      include Jenkins::Helper
 46:  
 47>>     provides :jenkins_command
 48:  
 49:      def load_current_resource
 50:        @current_resource ||= Resource::JenkinsCommand.new(new_resource.command)
 51:      end
 52:  
 53:      #
 54:      # This provider supports why-run mode.
 55:      #
 56:      def whyrun_supported?

**Comment by iennae** [comment]
Your supplied fix won't make this cookbook Chef 11 backwards compatible. You could use an earlier version of the cookbook and pin to that version that predates the current cookbook. In the near future we will be rewriting this cookbook and it will be Chef 12.5+.

**Comment by cheeseplus** [comment]
Closing this as we're not going to implement anything for Chef 11 at this point.
