### ISSUE TITLE
credentials_password.rb: wrong number of arguments (1 for 0)

### ISSUE THREAD

**Issue by peterfroehlich** [chef-cookbooks/jenkins#430]
We get an error using the credentials part of your cookbook:  

```
ArgumentError
-------------
wrong number of arguments (1 for 0)


Cookbook Trace:
---------------
  /var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:28:in `<class:JenkinsPasswordCredentials>'
  /var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:27:in `<class:Chef>'
  /var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:26:in `<top (required)>'


Relevant File Content:
----------------------
/var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:


Generated at 2015-12-02 16:57:29 +0100
ArgumentError: wrong number of arguments (1 for 0)
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/resource/lwrp_base.rb:69:in `resource_name'
/var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:28:in `<class:JenkinsPasswordCredentials>'
/var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:27:in `<class:Chef>'
/var/cache/chef/cookbooks/gf_jenkins/libraries/credentials_password.rb:26:in `<top (required)>'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.10.4/lib/chef/run_context/cookbook_compiler.rb:179:in `load'
```

**Versions:** 
Chef-Version 11.10.4
Ruby 1.9.1 (and hoping that an upgrade to 1.9.3 is not the fix)

We found that a lot of other cookbook have the exact same error, and that the fix is upgrading to Chef 12. You state that Chef 11.x is supported, is that outdated?

**Comment by downneck** [comment]
we're getting this as well, in a different file.

`Starting Chef Client, version 11.8.2
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef-solo/chef/config/cookbooks/jenkins/libraries/command.rb
================================================================================


ArgumentError
-------------
wrong number of arguments (1 for 0)


Cookbook Trace:
---------------
  /var/chef-solo/chef/config/cookbooks/jenkins/libraries/command.rb:27:in `<class:JenkinsCommand>'
  /var/chef-solo/chef/config/cookbooks/jenkins/libraries/command.rb:26:in `<class:Chef>'
  /var/chef-solo/chef/config/cookbooks/jenkins/libraries/command.rb:25:in `<top (required)>'


Relevant File Content:
----------------------
/var/chef-solo/chef/config/cookbooks/jenkins/libraries/command.rb:

 20:  #
 21:  
 22:  require_relative '_helper'
 23:  require_relative '_params_validate'
 24:  
 25:  class Chef
 26:    class Resource::JenkinsCommand < Resource::LWRPBase
 27>>     resource_name :jenkins_command
 28:  
 29:      # Chef attributes
 30:      identity_attr :command
 31:  
 32:      # Actions
 33:      actions :execute
 34:      default_action :execute
 35:  
 36:      # Attributes



Chef Client failed. 0 resources updated
`

**Comment by AReshma** [comment]
I got the same error from jenkins/libraries/command.rb

[root@ip-172-31-92-117 tmp]# cat /var/cache/chef/chef-stacktrace.out
Generated at 2016-05-26 08:59:06 -0400
ArgumentError: wrong number of arguments (1 for 0)
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/resource/lwrp_base.rb:69:in `resource_name'
/var/cache/chef/cookbooks/jenkins/libraries/command.rb:27:in `<class:JenkinsCommand>'
/var/cache/chef/cookbooks/jenkins/libraries/command.rb:26:in `<class:Chef>'
/var/cache/chef/cookbooks/jenkins/libraries/command.rb:25:in `<top (required)>'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:191:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:191:in `block in load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:188:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:188:in `load_libraries_from_cookbook'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:99:in `block in compile_libraries'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:98:in `each'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/run_context.rb:88:in `load'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/policy_builder/expand_node_object.rb:73:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/client.rb:265:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/client.rb:429:in `do_run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/client.rb:213:in `block in run'
/opt/chef/embedded/lib/ruby/gems/1.9.1/gems/chef-11.12.4/lib/chef/client.rb:207:in `fork'

**Comment by iennae** [comment]
Apologies for the late response to your inquiry. 

We are no longer doing updates to this cookbook to support Chef version 11. If you are only having problems with the credentials resources, and you can't upgrade to Chef version 12, and a current version of Ruby, you might want to pin your cookbook to a working version that supports Chef version 11, and also pin your version of Jenkins, and the plugins that you are installing.
