### ISSUE TITLE
can't change nofile limits 

### ISSUE THREAD

**Issue by eovolkov** [chef-cookbooks/jenkins#432]
- Command: `...`
- OS: CentOs 6.6
- Cookbook Version: 2.4.1
- Ruby Version: ruby 2.1.6p336
- Rubygems Version:
- Chef Version: 12.5.1

We can't to change limits or use system limits while using template sv-jenkins-slave-run.erb 

```
#!/bin/sh

#
# This file was generated by Chef for <%= node['fqdn'] %>.
# Do NOT modify this file by hand.
#

exec 2>&1
cd <%= @options[:new_resource].remote_fs %>
exec chpst -u <%= @options[:new_resource].user %> \
  env HOME=<%= @options[:new_resource].remote_fs %> \
  JENKINS_HOME=<%= @options[:new_resource].remote_fs %> \
  <%= @options[:java_bin] %> \
<%- if @options[:new_resource].jvm_options -%>
  <%= @options[:new_resource].jvm_options %> \
<%- end -%>
  -jar <%= @options[:slave_jar] %> \
<%- if @options[:jnlp_secret] -%>
  -secret <%= @options[:jnlp_secret] %> \
<%- end -%>
  -jnlpUrl <%= @options[:jnlp_url] %>

```

But if we change chpst to sudo in this template it work.

Can you help us with this problem?

**Comment by debanne** [comment]
This pull request change the limits for the server: https://github.com/chef-cookbooks/jenkins/pull/493
For the slave, maybe it would work to modify /etc/security/limits.conf or you may need to adapt the PR.

**Comment by tas50** [comment]
Fixed on master
