### ISSUE TITLE
Jenkins master on Windows?

### ISSUE THREAD

**Issue by patrickgardella** [chef-cookbooks/jenkins#437]
I was trying the cookbook against a Windows Server which would run the Jenkins master server, and it fails ("Received unknown error code (2224)") when trying to create the new users. 

I see in version 2.0.0 that the README.md file removed the lines, so I thought it might work with Windows Server as the master now:

```
Server (Master) Recipe
* Ubuntu
* RHEL/CentOS 
```

The code looks pretty Linux specific now that I've looked into it.  Should those server requirements go back into the README.md or should it work for Windows?  

The error is:

```
       Recipe: jenkins::_master_war
         * user[jenkins] action create
           - alter user jenkins


           ================================================================================
           Error executing action `create` on resource 'group[jenkins]'
           ================================================================================

           ArgumentError
           -------------
           Received unknown error code (2224)

           Resource Declaration:
           ---------------------
           # In C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\jenkins\recipes\_master_war.rb

            34: group node['jenkins']['master']['group'] do
            35:   members node['jenkins']['master']['user']
            36:   system node['jenkins']['master']['use_system_accounts'] # ~FC048
            37: end
            38:

           Compiled Resource:
           ------------------
           # Declared in C:\Users\vagrant\AppData\Local\Temp\kitchen\cookbooks\jenkins\recipes\_master_war.rb:34:in `from_file'

           group("jenkins") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             group_name "jenkins"
             members ["jenkins"]
             declared_type :group
             cookbook_name :jenkins
             recipe_name "_master_war"
             system true
           end


       Running handlers:
       [2015-12-16T07:39:48-08:00] ERROR: Running exception handlers
       Running handlers complete
       [2015-12-16T07:39:48-08:00] ERROR: Exception handlers complete
       Chef Client failed. 1 resources updated in 10 seconds
       [2015-12-16T07:39:48-08:00] FATAL: Stacktrace dumped to C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/chef-stacktrace.out
       [2015-12-16T07:39:48-08:00] FATAL: ArgumentError: group[jenkins] (jenkins::_master_war line 34) had an error: ArgumentError: Received unknown error code (2224)
```

**Comment by AdrianMW** [comment]
Hey,

I get the same error when running this on Windows Server 2012 R2:

group[jenkins] (jenkins::_master_war line 34) had an error: ArgumentError: The account already exists.

Interestingly this is a fresh copy of Windows with nothing on it so shouldn't be any conflicts

I tried installing Java separately first but that didn't make a difference.

The recipe mentions windows 

Cheers

**Comment by sernapallyanurag** [comment]
Have you found any work around for this?
Even I am facing the same issue.

**Comment by AdrianMW** [comment]
Hey,

I ended up doing the Jenkins install manually in the end and then using the cookbook for the rest of configuration (like creating users etc):

```
directory "C:\\Components" do
  action :create
  recursive true
end

remote_file "C:\\Components\\jenkins.zip" do
   source 'http://mirrors.jenkins-ci.org/windows/jenkins-1.658.zip'
end

seven_zip_archive 'seven_zip_source' do
  path      'C:\\Components\\jenkins'
  source    'C:\\Components\\jenkins.zip'
  overwrite true
end

windows_package 'Jenkins' do
  source 'C:\\Components\jenkins\jenkins.msi'
  installer_type :msi
end
```

However be a little careful as the cookbook doesn't work with Jenkins 2.0 yet

Cheers

**Comment by sernapallyanurag** [comment]
Thanks @AdrianMW for the suggestion and sorry for the delayed response.

**Comment by AdrianMW** [comment]
The existing cookbook can install plugins and create jobs on Windows after you install Jenkins manually.

Again only with Jenkins version 1.6xx at the moment

**Comment by sernapallyanurag** [comment]
So I can use resource libraries of supermarket cookbook without any modification. I have used recipe installation, should I change any attribute files?

**Comment by cheeseplus** [comment]
Closing this one as we only support jenkins slaves for Windows and the questions have been answered. If someone wanted to add testing and support for Windows in other capacities that would be great but it's not currently in the plans.
