### ISSUE TITLE
Release anytime soon?

### ISSUE THREAD

**Issue by jason-riddle** [chef-cookbooks/jenkins#439]
There are a couple of features that have been added that I would like to make use of.

- The build action for the jenkins_job resource (https://github.com/chef-cookbooks/jenkins/commit/44ad368be1808323c4c2eff030e8088bd11b6dab)
- The jenkins_secret_text_credentials resource (https://github.com/chef-cookbooks/jenkins/pull/410)

As well as the following pull requests that I'm keeping an eye on that should be merged soon.

- Installing plugins behind a corporate proxy (https://github.com/chef-cookbooks/jenkins/pull/402)
- jenkins_view HWRP (https://github.com/chef-cookbooks/jenkins/pull/364)

The last release v2.4.1 was in September. Is there going to be a release anytime soon to include the above features?

**Comment by iennae** [comment]
@jason-riddle, Thanks for the inquiry. Apologies for the late response. The cookbook engineering team met with the current maintainers of the cookbook within Chef last week to set up a plan of action to start regularly releasing this cookbook. We're in the process of working out the 2.5 release to be coming very soon now, as well as future release cycles. We should have a date for release for version 2.5 this week, and I'll update this issue then. Thanks for your understanding and patience.

**Comment by iennae** [comment]
Apologies for not updating this earlier, but we have released this cookbook a few times at this point, although the issues and pull requests that you've mentioned are not on the plan yet. We're fixing some of the critical issues and updating tests slowly. 

https://github.com/chef-cookbooks/jenkins/pull/410 should have already been pulled in and released. 

As is PR #364 isn't going to get merged in, as we are moving towards current custom resources and migrating away from HWRPs.

**Comment by jason-riddle** [comment]
Sounds good. Thanks!
