### ISSUE TITLE
cookbook fails on Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by swade1987** [chef-cookbooks/jenkins#442]
Chef client - 12.6.0

```
==> default: Adding debian:Hellenic_Academic_and_Research_Institutions_RootCA_2011.pem
==> default: Adding debian:Security_Communication_RootCA2.pem
==> default: done.
==> default: Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Processing triggers for ca-certificates (20141019ubuntu0.14.04.1) ...
==> default: Updating certificates in /etc/ssl/certs... 0 added, 0 removed; done.
==> default: Running hooks in /etc/ca-certificates/update.d....
==> default: done.
==> default: done.
==> default: STDERR: invoke-rc.d: initscript jenkins, action "start" failed.
==> default: dpkg: error processing package jenkins (--configure):
==> default:  subprocess installed post-installation script returned error exit status 7
==> default: Errors were encountered while processing:
==> default:  jenkins
==> default: E: Sub-process /usr/bin/dpkg returned an error code (1)
==> default: ---- End output of apt-get -q -y install jenkins=1.647 ----
==> default: Ran apt-get -q -y install jenkins=1.647 returned 100
==> default: [2016-02-06T18:12:30+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.
```

**Comment by munjeli** [comment]
Me too. I'm able to run this successfully in kitchen-docker, but can't use the kitchen-ec2 driver successfully, nor manage a remote build with Packer in AWS. I'm using Chef Zero on Ubuntu 1404. For some reason the start script isn't working. Same error.

**Comment by geekifier** [comment]
👍

**Comment by iennae** [comment]
Hey folks,

Can you give more information about what you are running into here? Maybe you are using a specific recipe that has an issue? I've used a .kitchen.yml to verify a problem, and I'm not seeing an issue. @munjeli the issue you are having may be a different issue, if you could open up a separate issue if you are still having the issue, that would be appreciated. @geekifier, I didn't have to change the version to 2.0 here.

<details>
platforms:
  - name: ubuntu-14.04
    run_list:
      - apt::default
      - jenkins::java

suites:
  - name: default
    run_list: jenkins::master
</details>
<details>
➜  jenkins git:(master) ✗ kitchen converge default-ubuntu-1404
-----> Starting Kitchen (v1.8.0)
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Importing base box 'opscode-ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
       ==> default: Setting the name of the VM: kitchen-jenkins-default-ubuntu-1404_default_1470291350266_46814
       ==> default: Fixed port collision for 8080 => 9090. Now on port 2202.
       ==> default: Fixed port collision for 22 => 2222. Now on port 2203.
       ==> default: Clearing any previously set network interfaces...
       ==> default: Preparing network interfaces based on configuration...
           default: Adapter 1: nat
       ==> default: Forwarding ports...
           default: 8080 => 2202 (adapter 1)
           default: 22 => 2203 (adapter 1)
       ==> default: Running 'pre-boot' VM customizations...
       ==> default: Booting VM...
       ==> default: Waiting for machine to boot. This may take a few minutes...
           default: SSH address: 127.0.0.1:2203
           default: SSH username: vagrant
           default: SSH auth method: private key
           default: Warning: Connection timeout. Retrying...
           default:
           default: Vagrant insecure key detected. Vagrant will automatically replace
           default: this with a newly generated keypair for better security.
           default:
           default: Inserting generated public key within guest...
           default: Removing insecure key from the guest if it's present...
           default: Key inserted! Disconnecting and reconnecting using new SSH key...
       ==> default: Machine booted and ready!
       ==> default: Checking for guest additions in VM...
       ==> default: Setting hostname...
       ==> default: Machine not provisioned because `--no-provision` is specified.
       [SSH] Established
       Vagrant instance <default-ubuntu-1404> created.
       Finished creating <default-ubuntu-1404> (0m59.07s).
-----> Converging <default-ubuntu-1404>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.2.3...
       Removing non-cookbook files before transfer
       Preparing data
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
-----> Installing Chef Omnibus (install only if missing)
       Downloading https://www.chef.io/chef/install.sh to file /tmp/install.sh
       Trying wget...
       Download complete.
       ubuntu 14.04 x86_64
       Getting information for chef stable  for ubuntu...
       downloading https://omnitruck-direct.chef.io/stable/chef/metadata?v=&p=ubuntu&pv=14.04&m=x86_64
         to file /tmp/install.sh.1404/metadata.txt
       trying wget...
       sha1	6a92025699634228efb118bc2ac2cc556992b140
       sha256	d64a029bc5402e2c2e2e1ad479e8b49b3dc7599a9d50ea3cefe4149b070582be
       url	https://packages.chef.io/stable/ubuntu/14.04/chef_12.12.15-1_amd64.deb
       version	12.12.15
       downloaded metadata file looks valid...
       downloading https://packages.chef.io/stable/ubuntu/14.04/chef_12.12.15-1_amd64.deb
         to file /tmp/install.sh.1404/chef_12.12.15-1_amd64.deb
       trying wget...
       Comparing checksum with sha256sum...

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       You are installing an omnibus package without a version pin.  If you are installing
       on production servers via an automated process this is DANGEROUS and you will
       be upgraded without warning on new releases, even to new major releases.
       Letting the version float is only appropriate in desktop, test, development or
       CI/CD environments.

       WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING

       Installing chef
       installing with dpkg...
       Selecting previously unselected package chef.
(Reading database ... 38981 files and directories currently installed.)
       Preparing to unpack .../chef_12.12.15-1_amd64.deb ...
       Unpacking chef (12.12.15-1) ...
       Setting up chef (12.12.15-1) ...
       Thank you for installing Chef!
       Transferring files to <default-ubuntu-1404>
       Starting Chef Client, version 12.12.15
       Creating a new client identity for default-ubuntu-1404 using the validator key.
       resolving cookbooks for run list: ["apt::default", "jenkins::java", "jenkins::master"]
       Synchronizing Cookbooks:
         - apt (4.0.1)
         - jenkins (2.6.0)
         - compat_resource (12.10.7)
         - runit (1.8.0)
         - yum (3.11.0)
         - packagecloud (0.2.4)
         - yum-epel (0.7.0)
       Installing Cookbook Gems:
       Compiling Cookbooks...
       [2016-08-04T06:17:10+00:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
       [2016-08-04T06:17:10+00:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
       [2016-08-04T06:17:10+00:00] WARN: Here we go with the runit service
       Converging 20 resources
       Recipe: apt::default
         * file[/var/lib/apt/periodic/update-success-stamp] action nothing (skipped due to action :nothing)
         * apt_update[periodic] action periodic
           - update new lists of packages
           * directory[/var/lib/apt/periodic] action create (up to date)
           * directory[/etc/apt/apt.conf.d] action create (up to date)
           * file[/etc/apt/apt.conf.d/15update-stamp] action create_if_missing
             - create new file /etc/apt/apt.conf.d/15update-stamp
             - update content in file /etc/apt/apt.conf.d/15update-stamp from none to c399a7
             --- /etc/apt/apt.conf.d/15update-stamp	2016-08-04 06:17:10.955780915 +0000
             +++ /etc/apt/apt.conf.d/.chef-15update-stamp20160804-1530-n2tdgk	2016-08-04 06:17:10.955780915 +0000
             @@ -1 +1,2 @@
             +APT::Update::Post-Invoke-Success {"touch /var/lib/apt/periodic/update-success-stamp 2>/dev/null || true";};
           * execute[apt-get -q update] action run
             - execute apt-get -q update

         * execute[apt-get update] action nothing (skipped due to action :nothing)
         * execute[apt-get autoremove] action nothing (skipped due to action :nothing)
         * execute[apt-get autoclean] action nothing (skipped due to action :nothing)
         * directory[/var/cache/local] action create
           - create new directory /var/cache/local
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * directory[/var/cache/local/preseeding] action create
           - create new directory /var/cache/local/preseeding
           - change mode from '' to '0755'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * template[/etc/apt/apt.conf.d/10recommends] action create
           - create new file /etc/apt/apt.conf.d/10recommends
           - update content in file /etc/apt/apt.conf.d/10recommends from none to f41e1d
           --- /etc/apt/apt.conf.d/10recommends	2016-08-04 06:17:30.009261999 +0000
           +++ /etc/apt/apt.conf.d/.chef-10recommends20160804-1530-1skfl2a	2016-08-04 06:17:30.009261999 +0000
           @@ -1 +1,4 @@
           +# Managed by Chef
           +APT::Install-Recommends "1";
           +APT::Install-Suggests "0";
           - change mode from '' to '0644'
           - change owner from '' to 'root'
           - change group from '' to 'root'
         * apt_package[apt-transport-https] action install (up to date)
       Recipe: jenkins::java
         * apt_package[openjdk-7-jdk] action install
           - install version 7u101-2.6.6-0ubuntu0.14.04.1 of package openjdk-7-jdk
       Recipe: jenkins::_master_war
         * user[jenkins] action create
           - create user jenkins
         * group[jenkins] action create
           - alter group jenkins
           - replace group members with new list of members
         * directory[/var/lib/jenkins] action create
           - create new directory /var/lib/jenkins
           - change mode from '' to '0755'
           - change owner from '' to 'jenkins'
           - change group from '' to 'jenkins'
         * directory[/var/log/jenkins] action create
           - create new directory /var/log/jenkins
           - change mode from '' to '0755'
           - change owner from '' to 'jenkins'
           - change group from '' to 'jenkins'
       Recipe: runit::default
         * service[runit] action nothing (skipped due to action :nothing)
         * execute[start-runsvdir] action nothing (skipped due to action :nothing)
         * apt_package[runit] action install
         Recipe: <Dynamically Defined Resource>
           * cookbook_file[/tmp/kitchen/cache/preseed/runit/runit-2.1.1-6.2ubuntu3.seed] action create
             - create new file /tmp/kitchen/cache/preseed/runit/runit-2.1.1-6.2ubuntu3.seed
             - update content in file /tmp/kitchen/cache/preseed/runit/runit-2.1.1-6.2ubuntu3.seed from none to 9c6758
             --- /tmp/kitchen/cache/preseed/runit/runit-2.1.1-6.2ubuntu3.seed	2016-08-04 06:27:31.537261999 +0000
             +++ /tmp/kitchen/cache/preseed/runit/.chef-runit-2.1.1-6.2ubuntu3.seed20160804-1530-1rhg73k	2016-08-04 06:27:31.533261999 +0000
             @@ -1 +1,2 @@
             +runit   runit/signalinit        boolean true
           - preseed package runit
           - install version 2.1.1-6.2ubuntu3 of package runit
       Recipe: jenkins::_master_war
         * remote_file[/var/lib/jenkins/jenkins.war] action create
           - create new file /var/lib/jenkins/jenkins.war
           - update content in file /var/lib/jenkins/jenkins.war from none to 41f58e
           (file sizes exceed 10000000 bytes, diff output suppressed)
           - change owner from '' to 'jenkins'
           - change group from '' to 'jenkins'
       Recipe: <Dynamically Defined Resource>
         * service[jenkins] action nothing (skipped due to action :nothing)
       Recipe: jenkins::_master_war
         * runit_service[jenkins] action enable
           * ruby_block[restart_service] action nothing (skipped due to action :nothing)
           * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
           * directory[/etc/sv/jenkins] action create
             - create new directory /etc/sv/jenkins
             - change mode from '' to '0755'
           * template[/etc/sv/jenkins/run] action create
             - create new file /etc/sv/jenkins/run
             - update content in file /etc/sv/jenkins/run from none to ed2a6a
             --- /etc/sv/jenkins/run	2016-08-04 06:28:38.785261999 +0000
             +++ /etc/sv/jenkins/.chef-run20160804-1530-1teit3t	2016-08-04 06:28:38.785261999 +0000
             @@ -1 +1,19 @@
             +#!/bin/sh
             +
             +#
             +# This file was generated by Chef.
             +# Do NOT modify this file by hand.
             +#
             +
             +
             +exec 2>&1
             +cd /var/lib/jenkins
             +touch jenkins.start
             +exec chpst -u jenkins -U jenkins \
             +  env HOME=/var/lib/jenkins \
             +  JENKINS_HOME=/var/lib/jenkins \
             +  java  -jar jenkins.war \
             +  --httpPort=8080 \
             +  --httpListenAddress=0.0.0.0 \
             +
             - change mode from '' to '0755'
           * directory[/etc/sv/jenkins/log] action create
             - create new directory /etc/sv/jenkins/log
           * directory[/etc/sv/jenkins/log/main] action create
             - create new directory /etc/sv/jenkins/log/main
             - change mode from '' to '0755'
           * directory[/var/log/jenkins] action create (up to date)
           * template[/etc/sv/jenkins/log/config] action create
             - create new file /etc/sv/jenkins/log/config
             - update content in file /etc/sv/jenkins/log/config from none to e3b0c4
             (no diff)
             - change mode from '' to '0644'
           * link[/var/log/jenkins/config] action create
             - create symlink at /var/log/jenkins/config to /etc/sv/jenkins/log/config
           * template[/etc/sv/jenkins/log/run] action create
             - create new file /etc/sv/jenkins/log/run
             - update content in file /etc/sv/jenkins/log/run from none to d76c77
             --- /etc/sv/jenkins/log/run	2016-08-04 06:28:38.841261999 +0000
             +++ /etc/sv/jenkins/log/.chef-run20160804-1530-q30f1m	2016-08-04 06:28:38.841261999 +0000
             @@ -1 +1,9 @@
             +#!/bin/sh
             +
             +#
             +# This file was generated by Chef.
             +# Do NOT modify this file by hand.
             +#
             +
             +exec chpst -unobody logger -d -p local6.info -t [jenkins]
             - change mode from '' to '0755'
           * directory[/etc/sv/jenkins/env] action create
             - create new directory /etc/sv/jenkins/env
             - change mode from '' to '0755'
           * ruby_block[zap extra env files for jenkins service] action run (skipped due to only_if)
           * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
           * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
           * directory[/etc/sv/jenkins/control] action create
             - create new directory /etc/sv/jenkins/control
             - change mode from '' to '0755'
           * link[/etc/init.d/jenkins] action create
             - create symlink at /etc/init.d/jenkins to /usr/bin/sv
           * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
           * ruby_block[restart_service] action run
             * ruby_block[restart_service] action nothing (skipped due to action :nothing)
             * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
             * directory[/etc/sv/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/run] action create (up to date)
             * directory[/etc/sv/jenkins/log] action create (up to date)
             * directory[/etc/sv/jenkins/log/main] action create (up to date)
             * directory[/var/log/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/log/config] action create (up to date)
             * link[/var/log/jenkins/config] action create (up to date)
             * template[/etc/sv/jenkins/log/run] action create (up to date)
             * directory[/etc/sv/jenkins/env] action create (up to date)
             * ruby_block[zap extra env files for jenkins service] action run (skipped due to only_if)
             * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
             * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
             * directory[/etc/sv/jenkins/control] action create (up to date)
             * link[/etc/init.d/jenkins] action create (up to date)
             * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
             * directory[/etc/service] action create (up to date)
             * link[/etc/service/jenkins] action create
        - create symlink at /etc/service/jenkins to /etc/sv/jenkins
             * ruby_block[wait for jenkins service socket] action run
        - execute the ruby block wait for jenkins service socket
             - execute the ruby block restart_service
           * ruby_block[restart_log_service] action run
             * ruby_block[restart_service] action nothing (skipped due to action :nothing)
             * ruby_block[restart_log_service] action nothing (skipped due to action :nothing)
             * directory[/etc/sv/jenkins] action create (up to date)

































             * template[/etc/sv/jenkins/run] action create (up to date)
             * directory[/etc/sv/jenkins/log] action create (up to date)
             * directory[/etc/sv/jenkins/log/main] action create (up to date)
             * directory[/var/log/jenkins] action create (up to date)
             * template[/etc/sv/jenkins/log/config] action create (up to date)
             * link[/var/log/jenkins/config] action create (up to date)
             * template[/etc/sv/jenkins/log/run] action create (up to date)
             * directory[/etc/sv/jenkins/env] action create (up to date)
             * ruby_block[zap extra env files for jenkins service] action run (skipped due to only_if)
             * template[/etc/sv/jenkins/check] action create (skipped due to only_if)
             * template[/etc/sv/jenkins/finish] action create (skipped due to only_if)
             * directory[/etc/sv/jenkins/control] action create (up to date)
             * link[/etc/init.d/jenkins] action create (up to date)
             * file[/etc/sv/jenkins/down] action nothing (skipped due to action :nothing)
             * directory[/etc/service] action create (up to date)
             * link[/etc/service/jenkins] action create (up to date)
             * ruby_block[wait for jenkins service socket] action run
        - execute the ruby block wait for jenkins service socket
             - execute the ruby block restart_log_service
           * directory[/etc/service] action create (up to date)
           * link[/etc/service/jenkins] action create (up to date)
           * ruby_block[wait for jenkins service socket] action run
             - execute the ruby block wait for jenkins service socket

         * runit_service[jenkins] action restart (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 31/88 resources updated in 11 minutes 38 seconds
       Finished converging <default-ubuntu-1404> (12m23.32s).
-----> Kitchen is finished. (13m26.24s)
</details>

**Comment by munjeli** [comment]
This is so old I can't recall the issue. I've had issues with the cookbook and the most recent versions of Jenkins because of the new default security features.

**Comment by iennae** [comment]
@munjeli Thanks for letting me know. I'm in the process of updating this cookbook and working through issues. I'm going to go ahead and close this one. If you have more details for your current issues please do file them.
