### ISSUE TITLE
Error executing action `create` on resource 'template[/etc/apache2/sites-available/jenkins]' #1

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/jenkins#450]
```
============================================================================
```
# 

```
Error executing action `create` on resource 'template[/etc/apache2/sites-ava
```

ilable/jenkins]'
#     ============================================================================

```
Chef::Mixin::Template::TemplateError
------------------------------------
undefined method `[]' for nil:NilClass

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/jenkins/recipes/http_apache2.rb

 40: template "#{node[:apache][:dir]}/sites-available/jenkins" do
 41:   source      "apache_jenkins.erb"
 42:   owner       'root'
 43:   group       'root'
 44:   mode        '0644'
 45:   variables(
 46:     :host_name        => host_name,
 47:     :host_aliases     => node[:jenkins][:http_proxy][:host_aliases],
 48:     :listen_ports     => node[:jenkins][:http_proxy][:listen_ports],
 49:     :www_redirect     => www_redirect
 50:   )
 51:
 52:   if File.exists?("#{node[:apache][:dir]}/sites-enabled/jenkins")
 53:     notifies  :restart, 'service[apache2]'
 54:   end
 55: end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/jenkins/recipes/http_apache2.rb:40:i
```

n `from_file'

```
template("/etc/apache2/sites-available/jenkins") do
  action [:create]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  source "apache_jenkins.erb"
  variables {:host_name=>"xyz.i8.internal.cloudapp.net
```

", :host_aliases=>[], :listen_ports=>[80], :www_redirect=>false}
      declared_type :template
      cookbook_name "jenkins"
      recipe_name "http_apache2"
      owner "root"
      group "root"
      mode "0644"
      path "/etc/apache2/sites-available/jenkins"
      atomic_update true
    end

Where do I enable the mentioned variables? I am using chef supermarket jenkins cookbook and how do I get my correct Hostname as the host name mentioned above is azure Internal Fqdn

**Comment by cheeseplus** [comment]
These attributes haven't been part of the cookbook for quite some time - having been removed in https://github.com/chef-cookbooks/jenkins/commit/0e3406013df82fc1e3413feecf761a8a8df3d957. At this point any Apache/Nginx configuration is something done externally of the Jenkins cookbook.
