### ISSUE TITLE
 Error executing action `restart` on resource 'service[jenkins]' first chef client run

### ISSUE THREAD

**Issue by sernapallyanurag** [chef-cookbooks/jenkins#451]
Recipe: <Dynamically Defined Resource>
  * service[jenkins] action restart

    ================================================================================
    Error executing action `restart` on resource 'service[jenkins]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /usr/bin/sv restart /etc/service/jenkins ----
    STDOUT: fail: /etc/service/jenkins: unable to change to service directory: file does not exist
    STDERR:
    ---- End output of /usr/bin/sv restart /etc/service/jenkins ----
    Ran /usr/bin/sv restart /etc/service/jenkins returned 1

    Compiled Resource:
    ------------------
    # Declared in

    service("jenkins") do
      provider Chef::Provider::Service::Simple
      action [:nothing]
      supports {:restart=>true, :reload=>true, :status=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "jenkins"
      pattern "jenkins"
      start_command "/usr/bin/sv start /etc/service/jenkins"
      stop_command "/usr/bin/sv stop /etc/service/jenkins"
      status_command "/usr/bin/sv status /etc/service/jenkins"
      restart_command "/usr/bin/sv restart /etc/service/jenkins"
    end

Second time it runs fine
I am using 
Chef-server: 11.0.10
chef-client: 12.7.2
OS : Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty
Jenkins cookbook version: 2.4.1
Installation method:  .war

**Comment by iennae** [comment]
@sernapallyanurag Please confirm that you are still experiencing this issue with a current version of this cookbook. Reopen with the updated details if this is the case.

Thanks!
