### ISSUE TITLE
best way to augment PATH with custom paths

### ISSUE THREAD

**Issue by rojomisin** [chef-cookbooks/jenkins#457]
If one wants to use ruby in say like `/opt/chef/embedded/bin`, I see I can edit this sysconfig/jenkins file template, I can add `PATH=$PATH:/other/paths` which works...
https://github.com/chef-cookbooks/jenkins/blob/f86c138e3cdeb7f530549776085fe2761342269f/templates/default/jenkins-config-rhel.erb
but is there a better way to add to the PATH that jenkins will see?

**Comment by cheeseplus** [comment]
I'm not sure where this intersects with the cookbook functionality, could you explain a little bit more about what you're trying to do and how?

If it's no longer an issue or you've resolved it please do let us know so we can close this one out.
