### ISSUE TITLE
Xcode marked build as failure in jenkins

### ISSUE THREAD

**Issue by hajarbabour** [chef-cookbooks/jenkins#465]
I use Git to get the source code, and i build it with xcode but when i run the build is fail

ps: my .xcodeproj is located in workspace(platforms(ios(app.xcodeproj)))

This is part of the console in jenkins:

[workspace] $ /usr/bin/xcodebuild -list      
xcodebuild: error: The directory /Users/user/.jenkins/jobs/testArt/workspace 

does not contain an Xcode project or workspace.

Build step 'Xcode' marked build as failure

Finished: FAILURE

**Comment by iennae** [comment]
Hi,

It's not clear whether the problem you are reporting is related to the installation of jenkins using the chef cookbook, or just a jenkins failure where you are using xcode. Can you provide additional information about your environment?

**Comment by iennae** [comment]
@hajarbabour 

If you are still requiring help with this issue, please reopen with additional information. Thanks.
