### ISSUE TITLE
Jenkins over Https

### ISSUE THREAD

**Issue by vraluca** [chef-cookbooks/jenkins#467]
Hi there,

What should I do to make Jenkins run over HTTPS using this cookbook ? Even though I changed the following attributes, when I want to create a job with jenkins_job I receive this error :

> The Jenkins master at `http://localhost:8080' did not become ready within 60
>     seconds. On large Jenkins instances, you may need to increase the timeout to
>     240 seconds. Alternatively, Jenkins may have failed to start.
>     Jenkins can fail to start if:

_default['jenkins']['master']['port']=9443_
_default['jenkins']['master']['jenkins_args']='--httpPort=-1 --httpsPort=9443 --httpsKeyStore=<path_to_keystore> --httpsKeyStorePassword=<keystorepassword'_

Thank you in advance,
Raluca

**Comment by AbraxasJung** [comment]
node.default['jenkins']['master']['jenkins_args'] = "--httpsPort=9443 --httpsCertificate=<PATH_TO_CERT> --httpsPrivateKey=<PATH_TO_KEY"

**Comment by jmaass** [comment]
There's also a way using Java keystores, as we do:
```
    node.set['jenkins']['master']['jenkins_args'] = "--httpPort=8080 --httpsPort=#{https_port} " +
        "--httpsKeyStore=#{keystore} " +
        "--httpsKeyStorePassword=#{keystore_password}"
```

**Comment by tas50** [comment]
Closing as the solution is above
