### ISSUE TITLE
Interest in install_plugins recipe?

### ISSUE THREAD

**Issue by jhull123** [chef-cookbooks/jenkins#475]
### Cookbook version

2.4.1
### Chef-client version

Chef 11, 12
### Platform Details

RHEL, OEL
### Scenario:

I have cookbook that wrappers the Jenkins cookbook to provide some features that are specific to my organization's environment/need.

Along the way a added a install_plugins recipe that leverages the plugin resource.

Is there interest in a PR for this recipe? I somewhat figured this was intentionally left out of the cookbook as a design choice. If that is the case, I'd like to know more as I'm interested in good cookbook design. :smile:

Cheers!
Jason

**Comment by StephenKing** [comment]
Linking to your code in github is never wrong ;-)

**Comment by cheeseplus** [comment]
We could certainly look at the code but given we definitely want this to be a more resource driven cookbook so using the existing jenkins_plugin resource is what we do in test recipes/wrappers.
