### ISSUE TITLE
System Error Message: No mapping between account names and security IDs was done

### ISSUE THREAD

**Issue by ankitgupta07** [chef-cookbooks/jenkins#489]
### Cookbook version

[2.6.0]
### Chef-client version

Using it on chefdk - kitchen version - 1.8.0
### Platform Details

[Windows 2008 R2]
### Scenario:

I am getting an error - `System Error Message: No mapping between account names and security IDs was done` while using the jenkins_windows_slave resource. Apparently this was fixed with PR# https://github.com/chef-cookbooks/jenkins/pull/333, but its again broken somewhere down the line.
### Steps to Reproduce:

I am using the below code to achieve my objective -

jenkins_windows_slave "#{node['fqdn']}" do
    description "#{node['platform']} - #{node['platform_version']}"
    remote_fs 'E:/jenkins'
    labels      ['test2015']
    executors 1
    user    service_user
    password service_password
end
### Expected Result:

Ideally, it should create the windows slave and setup the jenkins service on the Windows system.
### Actual Result:

```                      \* file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/jenkins-key]
 action create[2016-07-19T06:54:13-07:00] WARN: Mode 600 includes bits for the o
wner, but owner is not specified
        (up to date)
           - Create jenkins_windows_slave[mywinslave]
           \* directory[E:/jenkins] action create (up to date)
           \* directory[E:/jenkins] action create

```
         ================================================================================
         Error executing action `create` on resource 'directory[E:/jenkins]'

         ================================================================================

         Chef::Exceptions::Win32APIError
         -------------------------------
         No mapping between account names and security IDs was done.
         ---- Begin Win32 API output ----
         System Error Code: 1332
         System Error Message: No mapping between account names and security IDs was done.
         ---- End Win32 API output ----

         Compiled Resource:
         ------------------
         # Declared in

         directory("E:/jenkins") do
    action [:create]
    retries 0
    retry_delay 2
    default_guard_interpreter :default
    path "E:/jenkins"
    recursive true
    rights [{:permissions=>:full_control, :principals=>".\\Deployman"}]
         end

         Platform:
         ---------
         x64-mingw32

       ================================================================================
       Error executing action `create` on resource 'jenkins_windows_slave[mywinslave]'
       ================================================================================

       Chef::Exceptions::Win32APIError
       -------------------------------
       directory[E:/jenkins] (dynamically defined) had an error: Chef::Exceptions::Win32APIError: No mapping between account names and security IDs was done
```

```
```

**Comment by ankitgupta07** [comment]
Does anybody have update on this issue?

**Comment by cheeseplus** [comment]
Errors like this are most often related to the user not existing - you can pass the resource a `user` property so that it doesn't just use the default. Given the age I'm closing this one but please do open an issue with modern versions of the cookbook and chef-client if the problem is still present.
