### ISSUE TITLE
For barebones Java recipe to work on Ubuntu, it is necessary to add an apt repo

### ISSUE THREAD

**Issue by davidcpell** [chef-cookbooks/jenkins#499]
### Cookbook version
I've run into this issue on `2.4.1` as well as `2.6`

### Chef-client version
`12.12.15`

### Platform Details
OSX 10.11.6
Test Kitchen + `kitchen-vagrant`

### Scenario:
Use the barebones Java recipe to install JDK 7 on an Ubuntu VM

### Steps to Reproduce:
1. `$ kitchen init` inside of a project that wraps this cookbook
2. Make sure that test kitchen's run list includes a recipe that includes `jenkins::java`
2. `$ kitchen converge default-ubuntu-1404` (have also tried with the `default-ubuntu-1604` that comes with the kitchen setup included in `chef generate cookbook`)

### Expected Result:
Install JDK 7 before installing Jenkins

### Actual Result:
` Error executing action 'install' on resource 'apt_package[openjdk-7-jdk]'` followed by a bunch of 404s in the stack trace

Basically in order for `apt` to install recent versions of Jenkins, you have to add an apt repository. In my own projects I've just used the repo mentioned in these installation instructions taken from the [Jenkins wiki](https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Ubuntu)):

```
wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
```

It looks like this repo is capable of double-duty since it provides what is necessary for JDK 7 and is also necessary for recent versions of Jenkins itself.

If this issue is considered valid by the maintainers, I'd be happy to submit a pull request to include this step to get the barebones Java recipe working with Ubuntu.

**Comment by davidcpell** [comment]
closed this to better understand the issue (specifically the relationship of the Jenkins source repo to the Java problem) before reopening

**Comment by tas50** [comment]
I'm in the process of removing all Java installation from this cookbook. Java really needs to be handled by the user with the Java cookbook. That allows for the user to specify openJDK vs. Oracle JDK and provide specific versions that match their setup.
