### ISSUE TITLE
Plugin install fails because .plugin_version() modifies requested version

### ISSUE THREAD

**Issue by jwm** [chef-cookbooks/jenkins#503]
### Cookbook version

2.6.0
### Chef-client version

12.12.15 (from chefdk 0.16.28-1)
### Platform Details

Ubuntu 14.04 (trusty) on EC2
### Scenario:

The `conditional-buildstep` plugin depends on `matrix-project` plugin version `1.0-beta-1`.
The `jenkins_plugin` resource fails to install `matrix-project` because it incorrectly rewrites the version to `1.0.pre.beta.pre.1`.
### Steps to Reproduce:

```
jenkins_plugin "conditional-buildstep" do
  action :install
end
```
### Expected Result:

The `conditional-buildstep` plugin and its dependencies should be installed.
### Actual Result:

The plugin install fails with:

```
* remote_file[/tmp/kitchen/cache/matrix-project-1.0.pre.beta.pre.1.plugin] action create[2016-08-09T06:15:40+00:00] WARN: remote_file[/tmp/kitchen/cache/matrix-project-1.0.pre.beta.pre.1.plugin] cannot be downloaded from http://updates.jenkins-ci.org/download/plugins/matrix-project/1.0.pre.beta.pre.1/matrix-project.hpi: 404 "Not Found"
```

`Chef::Provider::JenkinsPlugin.plugin_version` (https://github.com/chef-cookbooks/jenkins/blob/master/libraries/plugin.rb#L435-L439) uses `Gem::Version` for plugin version parsing, which rewrites the plugin's version to `1.0.pre.beta.pre.1`. This causes the Update Center download to fail.

In previous versions of Ruby, `Gem::Version` would raise an `ArgumentError` in this case, so `.plugin_version()` would fall through and return the unmodified version string:

```
[jwm@hobbes:s006 ~> /usr/bin/ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
[jwm@hobbes:s006 ~> /usr/bin/irb
irb(main):001:0> require 'rubygems/version'
=> false
irb(main):002:0> Gem::Version.new('1.0-beta-1')
ArgumentError: Malformed version number string 1.0-beta-1
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/version.rb:191:in `initialize'
        from (irb):2:in `new'
        from (irb):2
        from /usr/bin/irb:12:in `<main>'
```

but more recent versions rewrite the version instead:

```
[jwm@hobbes:s004 ~> ruby --version
ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-darwin13.0]
[jwm@hobbes:s004 ~> irb
irb(main):001:0> require 'rubygems/version'
=> false
irb(main):002:0> Gem::Version.new('1.0-beta-1')
=> #<Gem::Version "1.0.pre.beta.pre.1">
```

**Comment by jwm** [comment]
As a workaround, we're monkeypatching this in our local recipe that defines `jenkins_plugin` resources:

```
class Chef::Provider::JenkinsPlugin
  alias old_plugin_version plugin_version
  def plugin_version(version)
    return version if version == "1.0-beta-1"

    old_plugin_version(version)
  end
end
```

**Comment by gopisaba** [comment]
+1

**Comment by marcmillien** [comment]
We had the same error here, but seems like it was due to plugin installation order :). Changing this order solved the issue.

**Comment by dserodio** [comment]
What a strange behavior. It seems like the cookbook should use strings for representing plugin versions instead of `Gem::Version`
