### ISSUE TITLE
Default attributes cause Jenkins master to be installed with version incompatible with this cookbook

### ISSUE THREAD

**Issue by sterago** [chef-cookbooks/jenkins#504]
### Cookbook version

2.6.0
### Chef-client version

12.12.15
### Platform Details

Ubuntu 15.04
### Scenario:

Installing Jenkins master
### Steps to Reproduce:

Create a basic wrapper recipe that includes the minimum required to install the Jenkins master via this cookbook:

```
include_recipe 'jenkins::java'
include_recipe 'jenkins::master'
```
### Expected Result:

Jenkins is installed with a version that is compatible with the cookbook, i.e. < 2.X
### Actual Result:

The latest stable version of Jenkins is installed (currently 2.19) which is not compatible with the cookbook

I am probably missing something, but is it possible to mention proper steps to get started with this cookbook in the README file, or, if this is a real issue, mention it somewhere in the same file?

**Comment by hernan82arg** [comment]
Same here...

**Comment by gugahoi** [comment]
On top of that there doesnt even seem to be a way to specify a version since only the latest is included in the apt-repo which is at 2.7.4 as of this moment.

**Comment by hernan82arg** [comment]
I've specified war installation method and downgraded to a version that the cookbook works for now...

**Comment by gugahoi** [comment]
which version is that?

**Comment by hernan82arg** [comment]
I'm using 1.642

**Comment by jmaass** [comment]
The following attributes work for me:

default['jenkins']['master']['install_method'] = 'package'
default['jenkins']['master']['use_system_accounts'] = false
default['jenkins']['master']['home'] = '/opt/app/jenkins'
default['jenkins']['master']['host'] = 'localhost'
default['jenkins']['master']['port'] = '8080'
default['jenkins']['master']['endpoint'] = "http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}/"
default['jenkins']['master']['jvm_options'] = '-Dhudson.diyChunking=false -Djenkins.install.runSetupWizard=false ' \
                                              '-Djenkins.slaves.JnlpSlaveAgentProtocol3.enabled=true'

default['jenkins']['executor']['timeout'] = 300

default['packagecloud']['proxy_host'] = node['mnet_jenkins']['proxy_host']
default['packagecloud']['proxy_port'] = node['mnet_jenkins']['proxy_port']

Contrary to the documentation and the comments in the text, node['jenkins]['master']['host'], node['jenkins']['master']['port'] AND node['jenkins']['master']['endpoint'] MUST be set if you want to install a slave. The cookbook does NOT reliably determine the endpoint from the first two attributes alone.

**Comment by sterago** [comment]
Thanks Jörg. What version gets installed using those attributes?

**Comment by jmaass** [comment]
The most current one, 2.23.

**Comment by cheeseplus** [comment]
With 5.0.0 release we're support 2.x up so this can be closed.
