### ISSUE TITLE
Feature Request: Return output of jenkins_command

### ISSUE THREAD

**Issue by jmaass** [chef-cookbooks/jenkins#525]
We currently have an issue with the Jenkins cookbook because we want to version lock the plugins we install. Of course, one could define a hash similar to:

```
plugins = {
  'bla' => '1.0',
  'blub' => '2.0
}
```

and then iterate over that hash. While that works in principle, it is actually a lot of work to keep the list up to date, especially when there's a lot of plugins to be installed.

So, we figured that on the first run, we'd just leave the version information out of the hash and install the most current version of each plugin, then use `jenkins_command` to get the output of `list-plugins`, parse that and fill the hash with the plugin versions obtained from `jenkins_command`.

That does not work, simply because `jenkins_command` does not return the output of the `list-plugins` CLI command.

It would be very beneficial if `jenkins_command` could get a switch that allows the return of the output of the CLI command.

**Comment by cheeseplus** [comment]
There isn't really a way for a resource to return output - we've got some other PRs/issues already open regarding reworking plugin installation but this particular method isn't viable given how Chef works.
