### ISSUE TITLE
ERROR: anonymous is missing the Overall/Read permission

### ISSUE THREAD

**Issue by CESteinmetz** [chef-cookbooks/jenkins#526]
### Cookbook version
3.1.0

### Chef-client version
12.14.89

### Platform Details
AWS - Amazon Linux AMI (most current)

I have looked through past issues for the problem I am experiencing, and implemented the resolutions listed, but to no avail.
I am attempting to create the chef user so I can run the jenkins command via chef. As per the guidelines, I created a data bag with the private key, and set the node run state:
`key = OpenSSL::PKey::RSA.new(jenkins['private_key'])`
 `private_key = key.to_pem`
 `public_key  = "#{key.ssh_type} #{[key.to_blob].pack('m0')}"`
 `node.run_state[:jenkins_private_key] = private_key`

I then set up the user:
`jenkins_user 'chef' do`
  `full_name   'Chef Client'`
  `public_keys [public_key]`
`end`

During the chef run, I see the correct private key being saved to the /var/chef/cache/jenkins-key file, but the run fails when setting up the user:

  jenkins_user[chef] action create
  Recipe: <Dynamically Defined Resource>
  remote_file[/var/chef/cache/jenkins-cli.jar] action create (up to date)
  remote_file[/var/chef/cache/update-center.json] action create (up to date)
  file[/var/chef/cache/extracted-update-center.json] action create (up to date)
  file[/var/chef/cache/jenkins-key] action create (up to date)

    ========================================================================
    Error executing action `create` on resource 'jenkins_user[chef]'
    ========================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '6'
    ---- Begin output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20161012-2791-1hkppj ----
    STDOUT:
    STDERR: ERROR: anonymous is missing the Overall/Read permission
    ---- End output of "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20161012-2791-1hkppj ----
    Ran "java" -jar "/var/chef/cache/jenkins-cli.jar" -s http://localhost:8080 groovy /tmp/groovy20161012-2791-1hkppj returned 6

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:85:in `execute!'
    /var/chef/cache/cookbooks/jenkins/libraries/_executor.rb:138:in `groovy!'
    /var/chef/cache/cookbooks/jenkins/libraries/user.rb:101:in `block (2 levels) in <class:JenkinsUser>'
    /var/chef/cache/cookbooks/jenkins/libraries/user.rb:100:in `block in <class:JenkinsUser>'

When I log into my Jenkins Web UI using the admin creds, set the security level to 'Anyone can do anything', then run chef-client, everything runs properly, security is reset to only allow logged in users as specified, and all chef-client runs from that point forward work properly. However, I don't want to have to do this manual process.

**Comment by CESteinmetz** [comment]
I'm closing this out - error caused by cookbook incompatibility with Jenkins > 2.0

**Comment by espoelstra** [comment]
For visitors from the future, you can bypass this by passing in a JVM option to the cookbook via an attribute. Just add ` -Djenkins.install.runSetupWizard=false` to any other options you have, example given below.

```default['jenkins']['master']['jvm_options'] = '-Djava.io.tmpdir=/var/jenkins/tmp -Dhudson.model.UpdateCenter.never=true -Djenkins.install.runSetupWizard=false -Dhudson.model.ParametersAction.keepUndefinedParameters=true'```
