### ISSUE TITLE
Plugin install -> installed plugins are out of date

### ISSUE THREAD

**Issue by gregorskii** [chef-cookbooks/jenkins#528]
### Cookbook version

3.1.0
### Chef-client version

Packer chef-solo -> 12.15.19-1
### Platform Details

Google Compute Debian Jessie
### Scenario:

Plugin install with up to date plugin versions
### Steps to Reproduce:

Install plugins
### Expected Result:

Plugins are newest version and up to date
### Actual Result:

Immediately upon loading Jenkins, jenkins reports plugins cannot start because they require newer versions of dependencies

**Comment by gregorskii** [comment]
Upon a further look I think this is a combination of the issue I reported in #527. What is happening is the last version of a plugin installed is the one that remains, and if plugin X has a newer version, but plugin Y requires an older version plugin Y version remains.

**Comment by StephenKing** [comment]
I currently have the same problem. I would say that this goes in combination with your issue #527 that plugin installation is pretty screwed up. You can see our builds also [here](https://chef-ci.typo3.org/job/TYPO3-cookbooks/job/site-chefcitypo3org/job/develop/) (after _long_ time), because old plugin versions get installed.

Would it make sense to keep the installed plugins in `node.run_state` to avoid repetitive, slow work and installation of (old) plugins that finally break?

**Comment by Dispader** [comment]
I ran into this while installing the `github-oauth` plugin as well.  The bit that was shocking to me is that, through the Jenkins console on a converged machine, installing `github-oauth` (correctly) identified the minimum versions required by the plugin, but `jenkins_plugin` installs specific versions which are explicitly inappropriate (and un/re-installs those versions, which are older).

**Comment by Dispader** [comment]
It's of note that version dependencies explicitly in `/tmp/kitchen/cache/extracted-update-center.json` are being installed correctly.  It seems to be a problem with derived versions.

And, as I was typing that, I see that @StephenKing chimed in.  (And I could totally buy that explanation.)

In the case of `github-oauth`, it looks like it's getting `structs` `1.2` from the cached JSON of either the `job-dsl` or `junit` transient dependencies, both of which list `1.2` explicitly.  (`junit` is the last to mention `structs` in the cached JSON).

**Comment by StephenKing** [comment]
@Dispader have a look at #534

**Comment by cheeseplus** [comment]
Closing in favor of #534
