### ISSUE TITLE
Plugin Installation is borked

### ISSUE THREAD

**Issue by ehaselwanter** [chef-cookbooks/jenkins#534]
### Cookbook version

4.0.1
### Chef-client version

12.13.37
### Platform Details

jenkins-plugin-install-ubuntu-1404
### Scenario:

```
jenkins_plugin 'github-oauth' do
  version '0.21.1'
  install_deps true
  notifies :restart, 'service[jenkins]', :immediately
end

```

should install github-api 1.67 but it does install updatecenter latest (https://github.com/jenkinsci/github-oauth-plugin/blob/e804d0b7d454b066ba016561fe7a1ca3804771dd/pom.xml#L82)
### Steps to Reproduce:

```
include_recipe 'java::default'
include_recipe 'jenkins::master'

jenkins_plugin 'github-oauth' do
  version '0.21.1'
  install_deps true
  notifies :restart, 'service[jenkins]', :immediately
end
```
### Expected Result:

plugin github-api 1.67 ist installed
### Actual Result:

plugin version from update center is installed (at the time of writing 1.69

**Comment by ehaselwanter** [comment]
this definitely includes #527 and #528 were there is more to it. dependencies should be honoured depending on the actual manifest of the plugin you want to install. and latest is definitely *not* the best strategy for 'least surprise'

**Comment by StephenKing** [comment]
But this is a `>=` dependency, isn't it? Don't you agree that it should always install the newest dependencies? Otherwise we probably end up with many conflicts, if the exactly specified version is installed by the plugin.

Nevertheless, I'm also sitting here and debugging the same issues..

**Comment by StephenKing** [comment]
What I especially see is that [at this place](https://github.com/chef-cookbooks/jenkins/blob/0a130afb654a6235c8b228f8e5245d5b7c254f3d/libraries/plugin.rb#L382), the 'MANIFEST.MF' never exists in the extracted, but only the `.jpi` files. I'm just digging into, if we could just read the file from the zipped `.jpi`.

**Comment by ehaselwanter** [comment]
@StephenKing I'll push a WIP MR for discussion which does this. But I'm super unsure if we are on the right track with that.

what I found is that a lot of people struggle with the automation of a consistent jenkins install.

- https://groups.google.com/forum/m/#!topic/jenkinsci-issues/m_3ZQxGl89Y
- https://issues.jenkins-ci.org/browse/JENKINS-31094

especially this one looks interesting:

- https://issues.jenkins-ci.org/browse/JENKINS-31094?focusedCommentId=266134&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-266134

which leads to a completely different way of doing it (not the current `jenkins-cli plungin-install`

**Comment by StephenKing** [comment]
@ehaselwanter I admit that I didn't read all of this, but while it sounds nice, I think that's nothing that can help us immediately. Certainly, it will better fit with our way of thinking.

I tried to track down the issue mentioned above a bit (`METADATA.MF` is not available). It didn't lead me to correctly installed dependencies, yet, but I guess, we need to fix that we read correct dependencies also before the plugin is deployed (extracted) by Jenkins). The WIP can be found here: https://github.com/StephenKing/chef-cookbook-jenkins/tree/read-metadata-from-jpi

**Comment by StephenKing** [comment]
I think I made good progress. Now, plugin installation checks versions of currently installed plugins and upgrades them if needed.

I only end up with one single issue, with the log output [here](https://gist.github.com/StephenKing/50ff92dcdc4aee67e2a205c16deb25e1#file-chef-client-log-L28-L56). It seems as Jenkins or the cookbook isn't aware that there is a version 2.5 of the plugin.

**Comment by ehaselwanter** [comment]
my WIP is here: https://github.com/infralovers/jenkins/tree/GH-534

especially: https://github.com/infralovers/jenkins/commit/5eaaa1a612781d774ff1d20a1cbddcfba4925efe

which is a super ugly but working implementation.

I basically reversed the plugin install. read the new plugin MANIFEST.MF and install the exact version of the mentioned plugins, since I think it is not safe to just pull in the latest from update-center

**Comment by ehaselwanter** [comment]
I think the main thing to do right now is to define the install strategy(ies) we want to have.
My fallback for now will be to install jenkins to get a list of plugin + version and put that list with a no-deps install in a wrapper cookbook. still I would love to get a update strategy working.

**Comment by StephenKing** [comment]
I think that's pretty close to what I've done.

**Comment by ehaselwanter** [comment]
How to proceed?

**Comment by iennae** [comment]
@ehaselwanter do you happen to be at Chef Summit in Seattle this week?

**Comment by ehaselwanter** [comment]
no. I've been to ChefConf and Chef Summit London.

**Comment by iennae** [comment]
Ahh ok. Was curious to see if we could meet up in person to chat about this. It's cool, I'll take a look and update either this week or next week. Thanks so much!

**Comment by sgtcoolguy** [comment]
Hey - Just wanted to check in and see if there were any plans in this issue or elsewhere to do more "holistic" plugin management. Specifically, right now the resource assumes you pass it a single plugin name and optionally a version, etc. From my own usage, looping over a not-trivial set of plugins we want and choosing to install dependencies, it seems to pick older versions of dependent plugins and use those. So if two plugins I want to install mark the same dependency with different versions, it will be a "last one installed wins" situation which may not satisfy the version constraints of both. In effect I've had to manually list out all the plugin dependencies and add them to my set and turn off installing dependencies to get around it. Not to mention installing multiple versions of the same plugin wastes time and bandwidth since only one will "win".

Can a batch "plugins" resource be used where you pass along the full set of plugins and versions and then it effectively attempts to resolve the minimal set of dependencies that satisfy all the criteria, opting for the dependency versions that will match? (perhaps even pass in a strategy value whereby you choose to take the minimum version of a dependency that satisfies all requirements, or the latest version)

**Comment by StephenKing** [comment]
Both, @ehaselwanter's and my suggestions fix that (without offering a batch functionality). I'd also be happy to see a progress here.

**Comment by ehaselwanter** [comment]
@sgtcoolguy for now I ended up with:

- install jenkins and the plugins you want to have somewhere. let jenkins do the dependency resolution
- get the list of plugin + version 
- put that list with a no-deps plugin_install in a wrapper cookbook. 

this gives you a consistent install of jenkins + plugins.

the downside is the manual first step + the somewhat hidden way to get 'old' plugins working. this is due to the fact that jenkins itself has no native way (dashboard) to select non-latest versions. to counter that you can (once again a semi manual way) install plugin+version top level deps with the patched way we propose here and then get the list plugin:version for the wrapper cookbook.

**Comment by StephenKing** [comment]
How can we proceed here? I would say that both @ehaselwanter's and my patches solve a couple of annoying issues (falsely calculated dependencies, incredible slow installation). Without that, the cookbook is not usable for me.

**Comment by iennae** [comment]
Hey folks, one of the other chef cookbook engineers may be able to jump in here for now, but I'm on maternity leave until mid-Januaryish so I won't be working on this until then. Thanks for understanding!

**Comment by StephenKing** [comment]
Have a good time, @iennae!

**Comment by ehaselwanter** [comment]
@iennae have a good time :-)
@StephenKing I would really like to see a 'final' solution here too. I'm just not sure if we should go for the *manage dependencies in chef* route. from my stand point: the jenkins plugin install is not really designed for a *point in version dependency* installation. and the only thing working to be consistent with this is to reach a sort of .lock file or information. like with berks/gem ... 

and that is exactly what I'm doing right now: I do a whatever automated/manual installation of jenkins. get it to a know to work state and export the plugin 'name:version' list. this gives me the sort of lock file-ish approach were I'm able to bump my jenkins wrapper cookbook to a new version.

the inspection of manifest files and bootstrap a fresh jenkins to get to a new starting point for the scenario above could indeed be improved with our ideas about patching the current plugin install algorithm. 

what do you think?

**Comment by chazzly** [comment]
I'm just running into this and working through this at the moment.   I've read this thread, but admittedly, not all the back up links, so maybe this has already been addressed.

If there is a way to let Jenkins handle the dependencies?  Jenkins obviously knows how to resolve plug-in dependencies when installing through the GUI, so maybe there is a way to leverage that. 

That would seem ideal, rather than having any cookbook resolve dependencies (lock file or otherwise), so that we're only specifying what we care about.

I CARE about plug-in 'XYZ' - ver 1.2.3.  The fact that it needs ABC- 0.1.5 & DEF -2.1.1 is irrelevant, let Jenkins handle that.  And later when I add QRS - 1.0.0 which needs DEF - 2.1.0, it won't be downgraded and will be satisfied with the DEF already installed.

my $.02

**Comment by ehaselwanter** [comment]
the problem with that is that jenkins does a kind of `>=` to the dependencies. and not `=` so consider a workflow `test -> staging -> prod` with the same top level pinning. if you let jenkins doing the dependency resolution it fetches the newest possible.

I got burned by that behaviour with some plugins. especially in the pipeline area, which have a lot of updates.

**Comment by StephenKing** [comment]
@ehaselwanter while pinning each and every version of a plugin is definitely a good idea, I would still expect the cookbook to correctly handle dependency resolution (@chazzly Jenkins does not handle dependencies when installing plugins via the API).

To further proceed, I think it would be good to have feedback from the maintainers (ping @tas50 ?) regarding the points in which @ehaselwanter and my WIP suggestions differ.

- We need to unzip the `.jpi` file. Would it be preferred to install the `ark` cookbook as dependency, or `chef_gem rubyzip` in the master recipe?

**Comment by StephenKing** [comment]
To be able to update my own cookbook, I gave @ehaselwanter's approach a try (to explicitly list _all_ plugins and their versions, see [this code here](https://github.com/TYPO3-cookbooks/site-chefcitypo3org/commit/2b05f5070015bada2660b11addd57ea071d82a27)).
As expected, it dramatically speeds up provisioning (by 20min [in my case](https://chef-ci.typo3.org/job/TYPO3-cookbooks/job/site-chefcitypo3org/job/master/), build no 8 vs 11).

The same would be possible by fixing the cookbook's plugin resolution.

**Comment by Dispader** [comment]
@StephenKing Nice— I wound up doing the same thing, but I left off the versions and let the metadata choose the most recent plugin versions.

**Comment by Poohblah** [comment]
What's the status on this bug? I was trying to debug some broken plugins on a fresh Jenkins installation, and this bug ended up being the cause.  I would really prefer not to have to specify an exact version of all of my plugins in order to guarantee that they all work.

**Comment by BenLiyanage** [comment]
It would be great if this got fixed.

**Comment by tanner-bruce** [comment]
You can use this as a workaround if you only need the latest plugins. I saw someone mention somewhere that installing via the CLI does not install deps, but empirically this does not seem to be the case, i.e deps are installed. 

```ruby
remote_file '/tmp/jenkins-cli.jar' do
  source 'http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar'
  mode '0755'
end

plugins.each do |plugin|
  execute "Install #{plugin}" do
    live_stream true
    command "java -jar /tmp/jenkins-cli.jar -s http://127.0.0.1:8080 install-plugin #{plugin}"
    not_if "java -jar /tmp/jenkins-cli.jar -s http://127.0.0.1:8080 list-plugins | grep #{plugin}"
  end
end
```

**Comment by grv87** [comment]
There is now https://github.com/jenkinsci/plugin-installation-manager-tool
