### ISSUE TITLE
Jenkins install fails in Ubuntu 14.04

### ISSUE THREAD

**Issue by sean-kang** [chef-cookbooks/jenkins#549]
### Cookbook version
4.1.2

### Chef-client version
12.7.2
12.17.44

### Platform Details
Ubuntu 14.04

### Scenario:
Install Jenkins on Ubuntu 14.04

### Steps to Reproduce:
Use include_recipe 'jenkins::master' with default attributes.

### Expected Result:
Install Jenkins

### Actual Result:
It fails with the following error.

           invoke-rc.d: initscript jenkins, action "start" failed.
           dpkg: error processing package jenkins (--configure):
            subprocess installed post-installation script returned error exit status 7
           Errors were encountered while processing:
            jenkins
           E: Sub-process /usr/bin/dpkg returned an error code (1)
           ---- End output of apt-get -q -y install jenkins=2.37 ----
           Ran apt-get -q -y install jenkins=2.37 returned 100

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_package.rb

            35:   package 'jenkins' do
            36:     version node['jenkins']['master']['version']
            37:   end
            38:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/jenkins/recipes/_master_package.rb:35:in `from_file'

           apt_package("jenkins") do
             package_name "jenkins"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "jenkins"
             recipe_name "_master_package"
           end

**Comment by StephenKing** [comment]
Test-kitchen suite `smoke-package-latest-ubuntu-1404` works for me.

**Comment by mikemoate** [comment]
I've seen this also, https://issues.jenkins-ci.org/browse/JENKINS-31814 seems to be the relevant issue in Jenkins.

I can also confirm running `apt-get install default-jre-headless` before including the recipe solves the problem.

It seems that allowing the jenkins package to 'pull' this dependency in within the same apt run fails to work.

**Comment by cheeseplus** [comment]
Granted I've merged a bunch of new code that has yet to be released but I haven't seen this issue - are you running a java recipe (whether from the java cookbook or the included one) @sean-kang?

**Comment by cheeseplus** [comment]
This appears to be resolved and we'll be releasing a new version soon.
