### ISSUE TITLE
environment uppercase and lowercase version

### ISSUE THREAD

**Issue by gimler** [chef-cookbooks/jenkins#555]
### Cookbook version
jenkins (2.4.1)

### Chef-client version
Chef: 11.18.12

### Scenario:
I try to set the environments for my slaves.

### Steps to Reproduce:
```
environment(http_proxy: '', https_proxy: '', no_proxy: '', HTTP_PROXY: '', HTTPS_PROXY: '', NO_PROXY: '')
```
### Expected Result:
6 environment entries on slave

### Actual Result:
only the first 3 values

**Comment by cheeseplus** [comment]
This is a very old version of the cookbook and an even older version of Chef. Please open an issue with modern versions if this is still an issue.
