### ISSUE TITLE
windows slave user and "logon as a service"

### ISSUE THREAD

**Issue by LuneraSteve** [chef-cookbooks/jenkins#601]
### Cookbook version
5.0.0

### Chef-client version
12.19.36

### Platform Details
Windows 2016 running under test-kitchen

### Scenario:
I'm trying to create a jenkins windows slave without having to know the password of the user account in question.

I see some references to this subject here: https://github.com/chef-cookbooks/jenkins/pull/376 but don't see any notes on how to implement it.

### Steps to Reproduce:

```ruby
jenkins_windows_slave node.name do
  remote_fs 'c:\jenkins'
  user 'Administrator'
  service_name 'jenkins-windows'
end
```

### Expected Result:
A connected and running jenkins slave.  What am I missing here?  If I specify user 'vagrant' and password 'vagrant' it works fine.  My guess is that the vagrant user already has the right privileges.  Outside of test-kitchen I'll be running this on AWS and I won't (and don't want to) have access to the passwords.

### Actual Result:
```
           Chef::Exceptions::Service
           -------------------------
           windows_service[jenkins-windows] (dynamically defined) had an error: Chef::Exceptions::Service: Service windows_service[jenkins-windows] did not start due to a logon failure (error 1069): possibly the specified user '' does not have the 'log on as a service' privilege, or the password is incorrect.
```

**Comment by emmanuelguerin** [comment]
On Windows, it is not possible to do this without the password for the user. One way is to use chef vault to store your passwords safely for chef to use.

I also seem to recall that the version of winsw set as default in the jenkins_windows_slave resource as issues with setting the 'log on as a service' privilege. I use the following attributes to select a more recent one:
```groovy
  winsw_url 'http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/1.18/winsw-1.18-bin.exe'
  winsw_checksum '73d9e44d61e9b52fb22b684bc621d9bc247473b7625e3f2fc8a2d16cc0443d18'
```

**Comment by LuneraSteve** [comment]
Is there a way to create a windows user and assign this privilege to it during a chef run?  I didn't see anything in the windows cookbook.

**Comment by emmanuelguerin** [comment]
If I'm not mistaken, winsw will do the appropriate thing, when it will
setup the jenkins service in the `jenkins_windows_slave` resource,

But you must create the user first using the standard Chef resource.

**Comment by LuneraSteve** [comment]
Thanks for sending over the new attributes.  I was able to put those in place, but no change happened.  From what I understand of what you wrote, it sounds like:

1.  Make User
2. Create Slave and toss in the winsw_url and winsw_checksum.  The winsw code will upgrade your new user to "logon as service" privileged 
3.  Everybody's happy

Here is my code for making this happen:
```ruby
# create jenkins user
user 'jenkins'
group 'Administrators' do
  action :modify
  members 'jenkins'
  append true
end

# create jenkins slave
jenkins_windows_slave node.name do
  remote_fs 'c:\jenkins'
  user 'jenkins'
  service_name 'jenkins-windows'
  winsw_url 'http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/1.18/winsw-1.18-bin.exe'
  winsw_checksum '73d9e44d61e9b52fb22b684bc621d9bc247473b7625e3f2fc8a2d16cc0443d18'
end
```
And here is the error:
```
           ================================================================================
           Error executing action `create` on resource 'jenkins_windows_slave[windows-windows-2016]'
           ================================================================================
           
           Chef::Exceptions::Service
           -------------------------
           windows_service[jenkins-windows] (dynamically defined) had an error: Chef::Exceptions::Service: Service windows_service[jenkins-windows] did not start due to a logon failure (error 1069): possibly the specified user '' does not have the 'log on as a service' privilege, or the password is incorrect.
           
           Resource Declaration:
           ---------------------
           # In C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/jenkins-windows/recipes/jenkins.rb
           
            31: jenkins_windows_slave node.name do
            32:   remote_fs 'c:\jenkins'
            33:   user 'jenkins'
            34:   #password 'vagrant'
            35:   service_name 'jenkins-windows'
            36:   winsw_url 'http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/1.18/winsw-1.18-bin.exe'
            37:   winsw_checksum '73d9e44d61e9b52fb22b684bc621d9bc247473b7625e3f2fc8a2d16cc0443d18'
            38: end
           
           Compiled Resource:
           ------------------
           # Declared in C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/jenkins-windows/recipes/jenkins.rb:31:in `from_file'
           
           jenkins_windows_slave("windows-windows-2016") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_windows_slave
             cookbook_name "jenkins-windows"
             recipe_name "jenkins"
             remote_fs "c:\\jenkins"
             user "jenkins"
             service_name "jenkins-windows"
             winsw_url "http://repo.jenkins-ci.org/releases/com/sun/winsw/winsw/1.18/winsw-1.18-bin.exe"
             winsw_checksum "73d9e44d61e9b52fb22b684bc621d9bc247473b7625e3f2fc8a2d16cc0443d18"
             slave_name "windows-windows-2016"
             description "Jenkins slave windows-windows-2016"
             labels []
             usage_mode "normal"
             pre_run_cmds []
             group "jenkins"
           end
           
           Platform:
           ---------
           x64-mingw32
```

**Comment by emmanuelguerin** [comment]
You need to set a password for you new user in by adding a password
attribute to the resource.
Then you need to provide that password to the jenkins_windows_slave
resource.

**Comment by LuneraSteve** [comment]
Ok, I added the password and got it working.  Man I don't want to know/store/maintain passwords!

Thanks for the help.

**Comment by LuneraSteve** [comment]
Ok, I added the password and got it working.  Man I don't want to know/store/maintain passwords!

Thanks for the help.
