### ISSUE TITLE
Windows Slave 'Endpoint' vs. 'Master.Host' usage

### ISSUE THREAD

**Issue by LuneraSteve** [chef-cookbooks/jenkins#605]
### Cookbook version
5.0.0

### Chef-client version
12.19.36

### Platform Details
AWS or Test-Kitchen+Vagrant

### Scenario:
I'm trying to figure out the best way to have a test-kitchen test env. and a production environment in the same cookbook and I'm running into issues with how to tell the windows slave where the jenkins master is.

### Steps to Reproduce:
You tell me?
But seriously, in .kitchen.yml I can put:

```    attributes:
      jenkins:
        master:
          host: '192.168.33.70'
```
in the suites section and connect to another local VM running as my jenkins master without issue.  This will override `default['jenkins']['master']['host']` in `attributes/default.rb`.  However, I found that when I am converging on a "production" node in AWS the jenkins.master.host setting in attributes is ignored and I need to use jenkins.master.endpoint instead.  I had to dig pretty deep to find this in the ohai attributes of the converged node.  jenkins.master.host was set according to my attributes settings, but jenkins.master.endpoint was set to localhost:8080.

Also, if I have jenkins.master.endpoint set in attributes/default, settings in .kitchen.yml are ignored.

### Expected Result:
I would like to see `test kitchen` converge a fully working test node that connects to a specified jenkins master as well as a chef-client run on a different machine connect to a different specified jenkins master.

Any suggestions would be appreciated.  Its probably me missing something.

### Actual Result:
Attributes are ignored and/or unpredictable?

**Comment by iennae** [comment]
It sounds like you have some interesting configuration going on in aws. Can you provide more details about your setup? 

If you look at the documentation within the [master.rb attributes file](https://github.com/chef-cookbooks/jenkins/blob/master/attributes/master.rb) (this is what the README is telling you to look at with regards to inline documentation), if you explicitly define  master['endpoint'], then  master['host'] is ignored. Take a look at the inline documentation starting here [master.rb#L166](https://github.com/chef-cookbooks/jenkins/blob/master/attributes/master.rb#L166) to understand more about the endpoint attribute.

**Comment by LuneraSteve** [comment]
Thanks for checking in.  

I'm looking to run `kitchen converge` and have a fulling working local windows slave, and then to promote my cookbook through our CI/CD to production and build an AWS working windows slave.  In test, the endpoint would be http://192.168.33.70:8080 and in prod the endpoint would be http://jenkins.domain.org:8080.

I had it working locally with attributes defined in `.kitchen.yml` pointing jenkins.master.host to the IP and had an attributes/default.rb file that had jenkins.master.host pointing to AWS.  What I found was that the attributes.rb file was accepted, but made no difference when running from chef server -- that is to say that running ohai on the chef server based node reported jenkins.master.host was populated, but jenkins.master.endpoint was localhost.

So, even though jenkins.master.host was set, for some reason it was ignored.

At this point I'm playing with setting an override_attributes environment setting and stubbing out an environment in kitchen.

I saw the documentation inline in the attributes file, but unless you actually know what you're looking for, the list won't give you any answers... "Don't know what you don't know, ya know?"

Perhaps if there was some information that showed how to create a basic working windows slave connection - what attributes need to be set, what resources to call, etc.  It took me a while to just "assume" that if I called `jenkins_windows_slave` on some random slave node that it would just work... and when I tried that it complained about trying to reach localhost, so I set the jenkins.master.host var and it moved forward... then I moved from test to prod and it broke halfway and I found the endpoint attribute (and so on).  Some of it is semi-obvious, like having to install Java on the slave node first.

I'd be happy to help out with the documentation, but I'm at a loss as to what to do "right", and don't know where to turn for more information.

As an example, When you setup a Jenkins SSH slave, you start on the master by setting up keys and then telling the master where to connect.  The SSH slave needs very little tied to it other than a shared key that works... but the windows slave is a completely different process.

Thanks!

**Comment by oberones** [comment]
In my cookbook, I use a common recipe (run by both master and slave) that cases the chef environment so that I can apply different host/port settings between dev and prod (we have other environments but I'm simplifying). For example:

case node.chef_environment

when 'jenkins_env_prod'

    # Use the host and port defined in the address databag for non-prod org
    node.default['jenkins']['master']['host'] = master_address['host']
    node.default['jenkins']['master']['port'] = master_address['port']

    # Use the public host and port defined in the address databag for non-prod org
    node.default['jenkins']['master']['public_host'] = master_address['public_host']
    node.default['jenkins']['master']['public_port'] = master_address['public_port']

else

    # Set the master's host entry to it's own IP
    node.default['jenkins']['master']['host'] = node['ipaddress']

    # Use kitchen-nodes to find the master and grab its IP for the slave
    jenkins_master = search(:node, 'run_list:jenkins_env\:\:master')
    node.default['jenkins']['master']['public_host'] = jenkins_master.first.ipaddress
    node.default['jenkins']['master']['public_port'] = 8080

end

The code above will grab the ip and port of the production master from a databag when converging in a prod environment, otherwise it will use kitchen-nodes to grab the ip of the master for the slave to use in its endpoint. As far as the endpoints go, I craft a slightly different one for master vs. in my slave. The master can use the direct host obviously, but the slave has to go through a reverse proxy so it uses the "public" host and port. 

From the master recipe:
node.default['jenkins']['master']['endpoint'] = "http://#{node['jenkins']['master']['host']}:#{node['jenkins']['master']['port']}#{node['jenkins']['master']['prefix']}/"

From the slave recipe
node.default['jenkins']['master']['endpoint'] = "http://#{node['jenkins']['master']['public_host']}:#{node['jenkins']['master']['public_port']}#{node['jenkins']['master']['prefix']}/"

Hope this helps.

**Comment by LuneraSteve** [comment]
The endpoint calculation logic didn't work for me.  I found a work around that uses environments.  Would still be happy to help with better documentation.
