### ISSUE TITLE
ssh protocol in executor causes error on "deprecated -remoting mode"

### ISSUE THREAD

**Issue by strocknar** [chef-cookbooks/jenkins#620]
### Cookbook version
5.0.1

### Chef-client version
Chef: 12.9.41

### Platform Details
CentOS Linux release 7.3.1611 (Core)

### Scenario:
Trying to create a slave using either JNLP (from the client) or SSH (from the master). Using the ssh protocol for the jenkins-cli.jar since we are behind authentication gives:
`ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel`

### Steps to Reproduce:
quick slave recipe
```
jenkins_jnlp_slave "lin_slave_#{node['hostname']}" do
  description "Linux Jenkins Slave: #{node['hostname']}"
  remote_fs   '/opt/jenkins'
  user        'jenkins'
  labels      ['linux']
  notifies :restart, 'service[jenkins-slave]', :immediately
end
```
attributes
```
{
  "jenkins": {
    "executor": {
      "protocol": "ssh",
      "cli_user": "jenkins"
    }
  }
}
```
### Expected Result:
jenkins-cli.jar would allow the creation of the slaves.
My understanding is that instead of adding `groovy #{file.path}` (which forces the -remoting option) the groovy script could be taken from STDIN (e.g. `cat ${file.path} | java -jar /path/to/jenkins-cli.jar -ssh -user #{user} groovy =`) and will work correctly

### Actual Result:
`ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel`

**Comment by BenLiyanage** [comment]
I'm also having this issue.  This was happening for me on jenkins version 2.51 and 2.50.  It was not happening on 2.46.

**Comment by dserodio** [comment]
Using a deprecated feature should be a warning, not an error, right?

**Comment by strocknar** [comment]
One would think. However, jenkins treats it as an error and does not allow the process to continue.

**Comment by isuftin** [comment]
Interestingly, when Jenkins starts, it does say that remoting is currently activated. One would think that this would allow this CLI command to move forward

:man_shrugging:

**Comment by varidots** [comment]
The error message is worded in a slightly confusing fashion. A more correct message would be 'The requested command can only be completed using the '-remoting' executor mode.'. This is because you are passing a file path to execute, not the contents, and that will only function with the '-remoting' mode.
It isn't actually attempting to to fall back to remoting, as far as I can tell.

I believe this does require a cookbook fix w.r.t. to how groovy scripts get executed in order to fix the resources on http and ssh executors.
