### ISSUE TITLE
Installing jenkins plugin using chef

### ISSUE THREAD

**Issue by pradheba123** [chef-cookbooks/jenkins#621]
### Cookbook version
[5.0.1]

### Platform Details
[Ubuntu]

### Scenario:
I'm new to chef and I'm trying to install jenkins plugins. I understand that the one of the ways to do it is to use the 'jenkins_plugin' resource and this downloads the plugins using the jenkins CLI. I suppose that this way requires internet to download the plugins. I am wondering is there a way to download these plugins locally in my workstation and reference them in a cookbook_file? So that, without internet the packages can be installed. If this is possible, kindly mention the steps to do it.

### Expected Result:
[To install jenkins plugins using chef]

**Comment by tanner-bruce** [comment]
Looks like this is not possible right now. You can see the relevant code here: https://github.com/chef-cookbooks/jenkins/blob/master/libraries/plugin.rb#L116

So at this time it is only from URL or from the update center. A PR to add local installation wouldn't be too involved.

**Comment by isuftin** [comment]
Looks like this was merged and was released to v5.0.3 

https://github.com/chef-cookbooks/jenkins/blob/v5.0.3/libraries/plugin.rb#L317
