### ISSUE TITLE
 Error executing action `start` on resource 'service[jenkins]'

### ISSUE THREAD

**Issue by gomteshhatginecognologix** [chef-cookbooks/jenkins#630]
### Cookbook version
[Cookbook 'jenkins', '= 2.4.1']

### Chef-client version
[chef-client version: 12.21.2]

### Platform Details
[bento/centos7.2]

### Scenario:
[Install jenkins using chef]

### Steps to Reproduce:
[
Berkshelf file to specify the cookbooks to be downloaded:

$ cat Berksfile
source "https://supermarket.chef.io"

cookbook "jenkins"
Step 2: Run chef-client in local mode

# Download cookbooks to local "cookbooks" directory
berks vendor cookbooks

# Run chef client in "local mode" 
sudo chef-client -z -r "jenkins::master"
]

### Expected Result:
[Jenkins should installed]

### Actual Result:
service[jenkins] action restart[2017-06-25T16:58:59+00:00] INFO: Processing service[jenkins] action restart (jenkins::_master_package line 74)

    
    ================================================================================
    Error executing action `start` on resource 'service[jenkins]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of /bin/systemctl --system restart jenkins ----
    STDOUT: 
    STDERR: Job for jenkins.service failed because the control process exited with error code. See "systemctl status jenkins.service" and "journalctl -xe" for details.
    ---- End output of /bin/systemctl --system restart jenkins ----
    Ran /bin/systemctl --system restart jenkins returned 1
    
    Resource Declaration:
    ---------------------
    # In /root/.chef/local-mode-cache/cache/cookbooks/jenkins/recipes/_master_package.rb
    
     74: service 'jenkins' do
     75:   supports status: true, restart: true, reload: true
     76:   action  [:enable, :start]
     77: end
    
    Compiled Resource:
    ------------------
    # Declared in /root/.chef/local-mode-cache/cache/cookbooks/jenkins/recipes/_master_package.rb:74:in `from_file'
    
    service("jenkins") do
      action [:enable, :start]
      supports {:status=>true, :restart=>true, :reload=>true}
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      service_name "jenkins"
      enabled nil
      running nil
      masked nil
      pattern "jenkins"
      declared_type :service
      cookbook_name "jenkins"
      recipe_name "_master_package"
    end
    
    System Info:
    ------------
    chef_version=12.21.2
    platform=centos
    platform_version=7.2.1511
    ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    program_name=chef-client worker: ppid=14911;start=16:58:52;
    executable=/opt/chefdk/bin/chef-client
    
[2017-06-25T16:58:59+00:00] INFO: Running queued delayed notifications before re-raising exception

Running handlers:
[2017-06-25T16:58:59+00:00] ERROR: Running exception handlers
Running handlers complete
[2017-06-25T16:58:59+00:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 07 seconds
[2017-06-25T16:58:59+00:00] FATAL: Stacktrace dumped to /root/.chef/local-mode-cache/cache/chef-stacktrace.out
[2017-06-25T16:58:59+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2017-06-25T16:58:59+00:00] ERROR: service[jenkins] (jenkins::_master_package line 74) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /bin/systemctl --system restart jenkins ----
STDOUT: 
STDERR: Job for jenkins.service failed because the control process exited with error code. See "systemctl status jenkins.service" and "journalctl -xe" for details.
---- End output of /bin/systemctl --system restart jenkins ----
Ran /bin/systemctl --system restart jenkins returned 1
[2017-06-25T16:58:59+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by StephenKing** [comment]
You have only Java 7 installed, right? Jenkins needs Java 8 starting from version 2.54 (and [Jenkins LTS 2.60.1 was just recently released](https://jenkins.io/changelog-stable/) as first LTS release with this requirement).

You run CentOS, I'm unsure if the same problem exists here as on Debian (which is a bit more evil, as the problem there happens even when you install Java 8 in advance and then Jenkins).
See [this issue](https://issues.jenkins-ci.org/browse/INFRA-1167), [my tweet](https://twitter.com/StGebert/status/879014460354121728, [my problem](https://chef-ci.typo3.org/blue/organizations/jenkins/TYPO3-cookbooks%2Fsite-chefcitypo3org/detail/master/72/pipeline)).

**Comment by iennae** [comment]
@gomteshhatginecognologix can you check the version of java you are installing?

**Comment by gomteshhatginecognologix** [comment]
@StephenKing and @iennae  its issue related to Java.I thought that while installing jenkins it will aslo install Java.But when I do like,
  cookbook 'java'
  cookbook 'jenkins', '= 2.4.1'
and run with sudo chef-client -z -r "java::default, jenkins::master" then it will install both Java and Jenkins successfully

**Comment by iennae** [comment]
Thanks for updating @gomteshhatginecognologix. We intentionally do not install java with this cookbook due to the myriad of ways that java could be installed.
