### ISSUE TITLE
Unable to add multiple plugins from plugin list

### ISSUE THREAD

**Issue by cognologixguru** [chef-cookbooks/jenkins#631]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
Jenkins - 5.0.2
### Chef-client version
[Version of chef-client in your environment]
Chef -12.21.2
### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
Operating System - CentOS-7.2
Virtual Machine Provider- Vagrant & Oracle VM VirtualBox

### Scenario:
[What you are trying to achieve and you can't?]

What I want to do? -
Option #1 - I want to add multiple plugins from my plugin file which contains list of plugins or short names, from where I can add/remove plugin in Jenkins.

Option #2 - Install plugins with given example
                  e.g jenkins_plugins 'greenballs'
                        ...
                        ...
                        jenkins_command 'resart'

Problem - 
For Option #1 - I am not able to read file from my recipe.
For Option #2 - System was asking for sudo/root authentication to install plugin

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
#1 - Sudo/Root user should be created (if necessary)
#2 - Plugin Installation should start with sudo/root permission
#3 - All listed plugins should be installed with jenkins installation.
#4 - List of installed and not installed plugin should be displayed.

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]

**Comment by grv87** [comment]
Try this approach: https://github.com/chef-cookbooks/jenkins/issues/534#issuecomment-265145360
