### ISSUE TITLE
Unable to create jenkins_user

### ISSUE THREAD

**Issue by cognologixguru** [chef-cookbooks/jenkins#633]
### Cookbook version
[Jenkins cookbook 2.4.1]

### Chef-client version
[chef-client version: 12.21.2]

### Platform Details
[Vagrant + Oracle VM VirtualBox + Bento/CentOS-7.2]

### Scenario:
I want to create user with admin permissions which can be used to install plugins in jenkins from list of plugins.

### Steps to Reproduce:

```ruby
require 'openssl'
require 'net/ssh'


unless node.run_state[:jenkins_private_key]

  # defaults to /etc/chef-jenkins-api.key
  key_path = node['jenkins_chefci']['jenkins_private_key_path']

  begin
    Chef::Log.info 'Trying to read private key from ' + key_path + ' for the chef user in jenkins'
    key = OpenSSL::PKey::RSA.new File.read(key_path)
    Chef::Log.info 'Successfully read existing private key'
  rescue
    key = OpenSSL::PKey::RSA.new 2048
    Chef::Log.info 'Generating new key pair for the chef user in jenkins in ' + key_path

    file key_path do
      content key.to_pem
      mode 0500
      sensitive true
    end
  end

  public_key = [key.ssh_type, [key.to_blob].pack('m0'), 'auto-generated key'].join(' ')

  # Create the Jenkins user with the public key
  jenkins_user 'chef' do
    id 'chef@' + Chef::Config[:node_name]
    full_name 'Chef Client'
    public_keys [public_key]
  end

  # Set the private key on the Jenkins executor
  node.run_state[:jenkins_private_key] = key.to_pem

end
```

### Expected Result:
[User : "Chef" should be created and these credentials should be available to add plugins]

### Actual Result:
Please file attached file
[errorFile_jenkins.pdf](https://github.com/chef-cookbooks/jenkins/files/1109047/errorFile_jenkins.pdf)

**Comment by tas50** [comment]
It looks like this is attempting to create the jenkins user using anonymous user auth against the jenkins server. You'll need to authenticate in order to create the user. There's some information on how to do that in the authentication section of the readme. Give it a try and open this back up if you're still having issues.
