### ISSUE TITLE
Cookbook will not pass Travis tests for ubuntu1404 due to new dependencies from 2.60.1 Debian package

### ISSUE THREAD

**Issue by olive42** [chef-cookbooks/jenkins#636]
### Cookbook version
5.0.2 (built from origin/master + patch https://github.com/criteo-forks/jenkins/commit/eaf370e99af4b5e0f970e2cbeca76448997b96f3)

### Chef-client version
13.2.20 (the one from Travis)

### Platform Details
Travis CI. See failing job at https://travis-ci.org/criteo-forks/jenkins/jobs/250017749

### Scenario:
Test a patch to the cookbook before a PR on a fork.

### Steps to Reproduce:
Try to run the Travis test on the HEAD revision of the chef-cookbooks/jenkins repository.

### Expected Result:
All tests pass.

### Actual Result:
The build for smoke-package-stable-ubuntu-1404 fails because the requirements for the Debian package of Jenkins have changed. It may be that java8-runtime-headless is not available on Ubuntu 14.04 by default on the image provided by Travis.

% dpkg-deb -I ~/Downloads/jenkins_2.46.3_all.deb
[...]
 Package: jenkins
 Version: 2.46.3
 Architecture: all
 Maintainer: Kohsuke Kawaguchi <kk@kohsuke.org>
 Installed-Size: 68732
 Depends: daemon, adduser, procps, psmisc, net-tools, default-jre-headless (>= 2:1.7) | java7-runtime-headless
[...]
% dpkg-deb -I ~/Downloads/jenkins_2.60.1-1_all.deb
[ ... ]
 Package: jenkins
 Version: 2.60.1-1
 Architecture: all
 Maintainer: Kohsuke Kawaguchi <kk@kohsuke.org>
 Installed-Size: 68996
 Depends: daemon, adduser, procps, psmisc, net-tools, default-jre-headless (>= 2:1.8) | java8-runtime-headless
[...]

**Comment by tas50** [comment]
It looks like Jenkins just went Java 8+ which means it no longer supports Ubuntu 14.04. I'll get the test suites and support updated. Thanks for the report

**Comment by StephenKing** [comment]
Same for Debian 8, which also ships Java 7 only (and I didn't find a way to fulfill the demand `default-jre-headless (>= 2:1.8) | java8-runtime-headless` or force apt to ignore it.

**Comment by tas50** [comment]
I also noted in the readme that package installs on Debian 8 will fail
