### ISSUE TITLE
node.run_state['jenkins_private_key'] silently ignored

### ISSUE THREAD

**Issue by llibicpep** [chef-cookbooks/jenkins#640]
### Cookbook version
5.0.3 (saw this earlier as well)

### Chef-client version
12.21.3

### Platform Details
CentOS 7

### Scenario:
Use CLI with -remoting and key access

### Steps to Reproduce:
Add auth strategy, create user and give him public key. Try to do something with CLI using `node.run_state['jenkins_private_key'] = something`.

### Expected Result:
`node.run_state['jenkins_private_key'] = something` should do the same as `node.run_state[:jenkins_private_key] = something`

### Actual Result:
`node.run_state['jenkins_private_key'] = something` silently ignored and auth failing.

This is necessary as Foodcritic seems to put a warning [FC001](http://www.foodcritic.io/#FC001) on the option that works.

**Comment by olive42** [comment]
node.run_state is a plain `Hash` and not a `Mash`, so `node.run_state[:jenkins_private_key]` is not the same as `node.run_state['jenkins_private_key']`. Add a `# ~FC001` comment to ignore the Foodcritic warning.

**Comment by tas50** [comment]
I've created a Foodcritic bug for this https://github.com/Foodcritic/foodcritic/issues/652

**Comment by iennae** [comment]
@llibicpep thanks for reporting. Thank you @olive42 for responding with such a clear response. As @olive42 has mentioned for now add an ignore for the foodcritic rule FC001 as it's incorrectly warning on this. A future foodcritic release will fix this.

**Comment by llibicpep** [comment]
Thanks, I did not know that `node.run_state` is not a `Mash`. TIL :)

**Comment by tas50** [comment]
Fixed in Foodcritic 11.3 which will ship with the next ChefDK. Thanks for the report

**Comment by damacus** [comment]
Closing this issue as stale. It was opened in 2018 and the cookbook has undergone significant changes since then. If this is still a problem with the current version of the cookbook, please open a new issue with updated details.
