### ISSUE TITLE
Allow custom service name for runit service

### ISSUE THREAD

**Issue by apatel-id** [chef-cookbooks/jenkins#649]
### Cookbook version
5.0.3

### Chef-client version
Chef: 12.19.36

### Platform Details
RHEL 7

### Scenario:
I need to support a deployment where Jenkins instance is called anything other than "jenkins".
This cookbook allows configuration of Jenkins'  user/group/home/logdir  but not the service name.

For consistency and cleanliness, it would be good if runit service name can be made configurable.

### Steps to Reproduce:
Deploy Jenkins using 'war' install method with customized Home and Log directory, using any name other than "jenkins".  
Notice that while Home and Log directories are customized the service name remains "jenkins", as it is hard coded.

### Expected Result:
The service name should follow name of deployed Jenkins instance.

### Actual Result:
Service name remains fixed as "jenkins"

**Comment by StephenKing** [comment]
Shouldn't you be able to change the service name using 

```ruby
edit_resource!('runit_service[jenkins]') do
  service_name 'my-jenkins'
end
```
in your wrapper cookbook?

**Comment by apatel-id** [comment]
@StephenKing Wow!.  Yes. I can.  
It honestly didn't occur to me to go this route.
Thank you.
