### ISSUE TITLE
Chef-client hangs on remote_file (jenkins-cli.jar)

### ISSUE THREAD

**Issue by madhead** [chef-cookbooks/jenkins#657]
### Cookbook version
5.0.4

### Chef-client version
Chef: 12.20.3

### Platform Details
Bento's Centos 6.9 image + Kitchen 1.17.0

### Scenario:
Trying to run `jenkins_plugins` on already converged Kitchen VM

### Steps to Reproduce:
I've create a VM is Kitchen and run `master` recipe so Jenkins Server is installed. Then I've run few `jenkins_plugin` resources successfully and installed some plugins in the same `converge` execution (in the same `chef-client` run). I've logged in the Jenkins (running in Kitchen's VM), restarted it (Jenkins) manually and saw that plugins in Admin UI. Also, I've **disabled remote CLI** access as it suggested by Jenkins. After that I've changed my data bag (that stores a list of plugins to install) and executed another `converge`.

### Expected Result:
Additional plugins are installed. Or at least the `converge` (`chef-client` run) fails with some sane error.

### Actual Result:
The `converge` hangs on this output:

    Recipe: abc-jenkins::plugins
      * jenkins_plugin[greenballs] action install[2017-09-17T00:00:03+00:00] INFO: Processing jenkins_plugin[greenballs] action install (abc-jenkins::plugins line 7)
    [2017-09-17T00:00:03+00:00] INFO: jenkins_plugin[greenballs] version 1.14 already installed - skipping
     (up to date)
      * jenkins_plugin[doktor] action install[2017-09-17T00:00:03+00:00] INFO: Processing jenkins_plugin[doktor] action install (abc-jenkins::plugins line 7)

      Recipe: <Dynamically Defined Resource>
        * remote_file[/tmp/kitchen/cache/update-center.json] action create[2017-09-17T00:00:03+00:00] INFO: Processing remote_file[/tmp/kitchen/cache/update-center.json] action create (dynamically defined)
     (up to date)
        * file[/tmp/kitchen/cache/extracted-update-center.json] action create[2017-09-17T00:00:05+00:00] INFO: Processing file[/tmp/kitchen/cache/extracted-update-center.json] action create (dynamically defined)
     (up to date)
    [2017-09-17T00:00:07+00:00] INFO: jenkins_plugin[doktor] version 0.0.1 already installed - skipping
         (up to date)
    Recipe: abc-jenkins::plugins
      * jenkins_plugin[ssh-slaves] action install[2017-09-17T00:00:07+00:00] INFO: Processing jenkins_plugin[ssh-slaves] action install (abc-jenkins::plugins line 7)

      Recipe: <Dynamically Defined Resource>
        * remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] action create[2017-09-17T00:00:07+00:00] INFO: Processing remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] action create (dynamically defined)
    [2017-09-17T00:00:09+00:00] INFO: remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] created file /tmp/kitchen/cache/ssh-credentials-1.6.1.plugin

          - create new file /tmp/kitchen/cache/ssh-credentials-1.6.1.plugin[2017-09-17T00:00:09+00:00] INFO: remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] updated file contents /tmp/kitchen/cache/ssh-credentials-1.6.1.plugin

          - update content in file /tmp/kitchen/cache/ssh-credentials-1.6.1.plugin from none to 831479
          (new content is binary, diff output suppressed)[2017-09-17T00:00:09+00:00] INFO: remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] owner changed to 497
    [2017-09-17T00:00:09+00:00] INFO: remote_file[/tmp/kitchen/cache/ssh-credentials-1.6.1.plugin] group changed to 498

          - change owner from '' to 'jenkins'
          - change group from '' to 'jenkins'
          - restore selinux security context
        * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create[2017-09-17T00:00:10+00:00] INFO: Processing remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create (dynamically defined)
     (up to date)

I've downloaded `/tmp/kitchen/cache/jenkins-cli.jar` file and it seems to be ok: `java -jar` works.

**Comment by slashpai** [comment]
chef-client is hanged on cli since you disabled remoting option which is default executor protocol https://github.com/chef-cookbooks/jenkins/blob/v5.0.4/attributes/executor.rb#L57 in cookbook. You can see errors in `/var/log/jenkins/jenkins.log` related to this. Since you disabled remoting option, you have to specify the cli option (http or ssh) explicitly in your wrapper cookbook.

Refer https://jenkins.io/doc/book/managing/cli/ for cli options
