### ISSUE TITLE
Cookbook is not compatible with Chef 13

### ISSUE THREAD

**Issue by oberones** [chef-cookbooks/jenkins#660]
### Cookbook version
5.0.4

### Chef-client version
13.4.19

### Platform Details
CentOS/RHEL 6.8 and 7.2

### Scenario:
Unable to connect a slave using JNLP or SSH connection methods when using chef-client 13.x

### Steps to Reproduce:
Simply clone master and run kitchen test. The jenkins slave test fixture cookbook will fail on both the create_jnlp and create_ssh recipes. 

### Actual Result:

`
RuntimeError
------------
can't modify frozen #<Class:#<Chef::Resource::JenkinsJnlpSlave:0x00000004bb4d48>>
`

### Logs

[converge.txt](https://github.com/chef-cookbooks/jenkins/files/1479125/converge.txt)
[stacktrace.txt](https://github.com/chef-cookbooks/jenkins/files/1479126/stacktrace.txt)

The following related issues have been opened for this, but one was closed for lack of details and the title of the other doesn't capture the full scope of the problem. 

https://github.com/chef-cookbooks/jenkins/issues/615
https://github.com/chef-cookbooks/jenkins/issues/634

**Comment by tas50** [comment]
This has been fixed on master and I'll be cutting a release once I fix a few other problems
