### ISSUE TITLE
Install JNLP Slave to run as LocalSystem - library forces domain in XML

### ISSUE THREAD

**Issue by Brantone** [chef-cookbooks/jenkins#693]
### Cookbook version
6.2.0

### Chef-client version
13.10.0

### Platform Details
Windows 2016 Server

### Scenario:
Install Jenkins slave as LocalSystem account

### Expected Result:
Install agent as JNLP and run as LocalSystem account

### Actual Result:
```
2018-08-01 07:04:08,635 INFO  - Installing the service with id 'jenkins-slave'
LookupAccountName failed: 1332
Failed to set logon as a service right
```

If `jenkins-slave.xml` has `<domain>.</domain>` in it, then it fails, but that line is removed it works; however. due to https://github.com/chef-cookbooks/jenkins/blob/master/libraries/slave_windows.rb#L275 there's no way domain is empty, thus https://github.com/chef-cookbooks/jenkins/blob/master/templates/jenkins-slave.xml.erb#L65 is redundant.

Will look at submitting PR.

**Comment by Brantone** [comment]
Actually, just realized, if pass:
```
user ' \\LocalSystem'
```
then it works, so if anything README should be updated ... will leave this ticket on chance it helps someone else

**Comment by mbaitelman** [comment]
This was fixed in [PR703](https://github.com/chef-cookbooks/jenkins/pull/703)

**Comment by Brantone** [comment]
👍
